  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.wds.w8006080802;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2010-8-13
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class TbFreightstandradBTVO extends SuperVO {
           
             public UFDouble tnumbermin;
             public UFTime ts;
             public UFDouble price;
             public UFDouble tnumbermax;
             public Integer dr;
             public String tc_pk;
             public String fs_pkbt;
             public String fjf; //
             public String bz; //
             public String standertype;
             public UFDouble standernum;
             

            /* public String dcompany;//
             public String dhz;//
             public UFDouble evennumber;//
*/            
             public String pk_wlxx;		 //
             public String pk_vdef1;	 
             public String pk_vdef2;	 
             public String pk_vdef3;	
             public String pk_vdef4;	 
             public String pk_vdef5;	
             public String pk_vdef6;	 
             public String pk_vdef7;	 
             public String pk_vdef8;	 
             public String pk_vdef9;	
             public String fr_customize1;	 
             public String fr_customize2;	 
             public String fr_customize3;	 
             public String fr_customize4;	 
             public String fr_customize5;	 
             public String fr_customize6;	 
             public String fr_customize7;	 
             public String fr_customize8;	 
             public String fr_customize9;	 
             public String fr_customize10;	 
             public String fr_customize11;	 
             public String fr_customize12;	 
             public String fr_customize13;	 
            
           
             

            /* public static final String DCOMPANY="dcompany";
             public static final String DHA="dhz";
             public static final String EVENNUMBER="evennumber";*/
             public static final String  PK_WLXX="pk_wlxx";   
             public static final String  TNUMBERMIN="tnumbermin";   
             public static final String  TS="ts";   
             public static final String  PRICE="price";   
             public static final String  TNUMBERMAX="tnumbermax";   
             public static final String  DR="dr";   
             public static final String  TC_PK="tc_pk";   
             public static final String  FS_PKBT="fs_pkbt";   
             public static final String  FJF="fjf";   
             public static final String  BZ="bz";   
             public static final String  PK_VDEF1="pk_vdef1";   
             public static final String  PK_VDEF2="pk_vdef2";   
             public static final String  PK_VDEF3="pk_vdef3";   
             public static final String  PK_VDEF4="pk_vdef4";   
             public static final String  PK_VDEF5="pk_vdef5";   
             public static final String  PK_VDEF6="pk_vdef6";   
             public static final String  PK_VDEF7="pk_vdef7";   
             public static final String  PK_VDEF8="pk_vdef8";   
             public static final String  PK_VDEF9="pk_vdef9";   
             public static final String  FR_CUSTOMIZE1="fr_customize1";   
             public static final String  FR_CUSTOMIZE2="fr_customize2";   
             public static final String  FR_CUSTOMIZE3="fr_customize3";   
             public static final String  FR_CUSTOMIZE4="fr_customize4";   
             public static final String  FR_CUSTOMIZE5="fr_customize5";   
             public static final String  FR_CUSTOMIZE6="fr_customize6";   
             public static final String  FR_CUSTOMIZE7="fr_customize7";   
             public static final String  FR_CUSTOMIZE8="fr_customize8";   
             public static final String  FR_CUSTOMIZE9="fr_customize9";   
             public static final String  FR_CUSTOMIZE10="fr_customize10";   
             public static final String  FR_CUSTOMIZE11="fr_customize11";   
             public static final String  FR_CUSTOMIZE12="fr_customize12";   
             public static final String  FR_CUSTOMIZE13="fr_customize13";   
             public static final String STANDERTYPE="standertype";
             public static final String STANDERNUM="standernum";
             
      
    
        public String getStandertype() {
				return standertype;
			}

			public void setStandertype(String standertype) {
				this.standertype = standertype;
			}

		public String getPk_wlxx() {
				return pk_wlxx;
			}

			public void setPk_wlxx(String pk_wlxx) {
				this.pk_wlxx = pk_wlxx;
			}

		/**
	   * 属性tnumbermin的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return UFDouble
	   */
	 public UFDouble getTnumbermin() {
		 return tnumbermin;
	  }   
	  
     /**
	   * 属性tnumbermin的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newTnumbermin UFDouble
	   */
	public void setTnumbermin(UFDouble newTnumbermin) {
		
		tnumbermin = newTnumbermin;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return UFDateTime
	   */
	 public UFTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newTs UFDateTime
	   */
	public void setTs(UFTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性price的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return UFDouble
	   */
	 public UFDouble getPrice() {
		 return price;
	  }   
	  
     /**
	   * 属性price的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newPrice UFDouble
	   */
	public void setPrice(UFDouble newPrice) {
		
		price = newPrice;
	 } 	  
       
        /**
	   * 属性tnumbermax的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return UFDouble
	   */
	 public UFDouble getTnumbermax() {
		 return tnumbermax;
	  }   
	  
     /**
	   * 属性tnumbermax的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newTnumbermax UFDouble
	   */
	public void setTnumbermax(UFDouble newTnumbermax) {
		
		tnumbermax = newTnumbermax;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性tc_pk的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return String
	   */
	 public String getTc_pk() {
		 return tc_pk;
	  }   
	  
     /**
	   * 属性tc_pk的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newTc_pk String
	   */
	public void setTc_pk(String newTc_pk) {
		
		tc_pk = newTc_pk;
	 } 	  
       
        /**
	   * 属性fs_pkbt的Getter方法.
	   *
	   * 创建日期:2010-8-13
	   * @return String
	   */
	 public String getFs_pkbt() {
		 return fs_pkbt;
	  }   
	  
     /**
	   * 属性fs_pkbt的Setter方法.
	   *
	   * 创建日期:2010-8-13
	   * @param newFs_pkbt String
	   */
	public void setFs_pkbt(String newFs_pkbt) {
		
		fs_pkbt = newFs_pkbt;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2010-8-13
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (fs_pkbt == null) {
			errFields.add(new String("fs_pkbt"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-8-13
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "tc_pk";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-8-13
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "fs_pkbt";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2010-8-13
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "tb_freightstandrad_b_t";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-8-13
	  */
	public TbFreightstandradBTVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2010-8-13
	 * @param newFs_pkbt 主键值
	 */
	 public TbFreightstandradBTVO(String newFs_pkbt) {
		
		// 为主键字段赋值:
		 fs_pkbt = newFs_pkbt;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-8-13
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return fs_pkbt;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-8-13
	  * @param newFs_pkbt  String    
	  */
	 public void setPrimaryKey(String newFs_pkbt) {
				
				fs_pkbt = newFs_pkbt; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2010-8-13
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "tb_freightstandrad_b_t"; 
				
	 }

	public String getFjf() {
		return fjf;
	}

	public void setFjf(String fjf) {
		this.fjf = fjf;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getPk_vdef1() {
		return pk_vdef1;
	}

	public void setPk_vdef1(String pk_vdef1) {
		this.pk_vdef1 = pk_vdef1;
	}

	public String getPk_vdef2() {
		return pk_vdef2;
	}

	public void setPk_vdef2(String pk_vdef2) {
		this.pk_vdef2 = pk_vdef2;
	}

	public String getPk_vdef3() {
		return pk_vdef3;
	}

	public void setPk_vdef3(String pk_vdef3) {
		this.pk_vdef3 = pk_vdef3;
	}

	public String getPk_vdef4() {
		return pk_vdef4;
	}

	public void setPk_vdef4(String pk_vdef4) {
		this.pk_vdef4 = pk_vdef4;
	}

	public String getPk_vdef5() {
		return pk_vdef5;
	}

	public void setPk_vdef5(String pk_vdef5) {
		this.pk_vdef5 = pk_vdef5;
	}

	public String getPk_vdef6() {
		return pk_vdef6;
	}

	public void setPk_vdef6(String pk_vdef6) {
		this.pk_vdef6 = pk_vdef6;
	}

	public String getPk_vdef7() {
		return pk_vdef7;
	}

	public void setPk_vdef7(String pk_vdef7) {
		this.pk_vdef7 = pk_vdef7;
	}

	public String getPk_vdef8() {
		return pk_vdef8;
	}

	public void setPk_vdef8(String pk_vdef8) {
		this.pk_vdef8 = pk_vdef8;
	}

	public String getPk_vdef9() {
		return pk_vdef9;
	}

	public void setPk_vdef9(String pk_vdef9) {
		this.pk_vdef9 = pk_vdef9;
	}

	public String getFr_customize1() {
		return fr_customize1;
	}

	public void setFr_customize1(String fr_customize1) {
		this.fr_customize1 = fr_customize1;
	}

	public String getFr_customize2() {
		return fr_customize2;
	}

	public void setFr_customize2(String fr_customize2) {
		this.fr_customize2 = fr_customize2;
	}

	public String getFr_customize3() {
		return fr_customize3;
	}

	public void setFr_customize3(String fr_customize3) {
		this.fr_customize3 = fr_customize3;
	}

	public String getFr_customize4() {
		return fr_customize4;
	}

	public void setFr_customize4(String fr_customize4) {
		this.fr_customize4 = fr_customize4;
	}

	public String getFr_customize5() {
		return fr_customize5;
	}

	public void setFr_customize5(String fr_customize5) {
		this.fr_customize5 = fr_customize5;
	}

	public String getFr_customize6() {
		return fr_customize6;
	}

	public void setFr_customize6(String fr_customize6) {
		this.fr_customize6 = fr_customize6;
	}

	public String getFr_customize7() {
		return fr_customize7;
	}

	public void setFr_customize7(String fr_customize7) {
		this.fr_customize7 = fr_customize7;
	}

	public String getFr_customize8() {
		return fr_customize8;
	}

	public void setFr_customize8(String fr_customize8) {
		this.fr_customize8 = fr_customize8;
	}

	public String getFr_customize9() {
		return fr_customize9;
	}

	public void setFr_customize9(String fr_customize9) {
		this.fr_customize9 = fr_customize9;
	}

	public String getFr_customize10() {
		return fr_customize10;
	}

	public void setFr_customize10(String fr_customize10) {
		this.fr_customize10 = fr_customize10;
	}

	public String getFr_customize11() {
		return fr_customize11;
	}

	public void setFr_customize11(String fr_customize11) {
		this.fr_customize11 = fr_customize11;
	}

	public String getFr_customize12() {
		return fr_customize12;
	}

	public void setFr_customize12(String fr_customize12) {
		this.fr_customize12 = fr_customize12;
	}

	public String getFr_customize13() {
		return fr_customize13;
	}

	public void setFr_customize13(String fr_customize13) {
		this.fr_customize13 = fr_customize13;
	}

	public UFDouble getStandernum() {
		return standernum;
	}

	public void setStandernum(UFDouble standernum) {
		this.standernum = standernum;
	}



/*	public String getDcompany() {
		return dcompany;
	}

	public void setDcompany(String dcompany) {
		this.dcompany = dcompany;
	}

	public String getDhz() {
		return dhz;
	}

	public void setDhz(String dhz) {
		this.dhz = dhz;
	}

	public UFDouble getEvennumber() {
		return evennumber;
	}

	public void setEvennumber(UFDouble evennumber) {
		this.evennumber = evennumber;
	} */
} 
