/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.hg.pu.pub;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.scm.pu.PuPubVO;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-11-01 10:37:18
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PlanVO extends SuperVO {
	private String creqwarehouseid; //需求仓库
	private String capplydeptid;  //申请部门
	private String capplypsnid; //申请人
	private String cyear; //年度
	private String cmonth;//月份
	private String cinvclassid;//物资分类
	private String caccperiodschemeid; //会计期间方案
	private String creqcalbodyid; //需求组织
	private String cplanprojectid; //计划项目
	private String csupplydeptid; //供货部门
	private String csupplycorpid;//供货单位
	private String pk_corp; //申请公司
	private Integer vbillstatus;
	private UFDate dbilldate;
	private UFDate dapprovedate;
	private UFBoolean fisclose;//  临时计划等为是否预留    月计划为打开关闭
	private String csourcebillno; //源年计划单据号
	private UFBoolean fisself;//  是否自制
	private String pk_busitype;//业务类型

	private UFDate denddate;
	private UFDate dstratdate;
	private UFDate dmakedate;
	private String vapproveid;
	private String vapprovenote;
	private String voperatorid;
	private String pk_billtype;
	private String vbillno;

	private String pk_defdoc19;	
	private String pk_defdoc10;
	private String vdef9;
	private String vdef10;
	private String pk_defdoc18;
	private String vdef15;
	private String pk_defdoc8;	
	private String vdef14;
	private String pk_defdoc5;
	private String vreserve1;
	private String vdef7;
	private String pk_defdoc7;
	private String pk_plan;
	private UFDouble nreserve8;
	private String vdef2;
	private String vdef16;
	private String vdef5;
	private String vmemo;
	private String pk_defdoc12;
	private String vdef19;
	private String pk_defdoc13;	
	private String pk_defdoc6;
	private String vdef4;
	private String vdef18;
	private String vreserve5;
	private UFDouble nreserve9;
	private String vdef17;
	private String pk_defdoc15;	
	private String pk_defdoc2;
	private String vdef1;
	private String vdef20;
	private String vdef8;
	private UFDouble nreserve7;
	private String pk_defdoc3;
	private String vreserve4;
	private String pk_defdoc17;
	private String pk_defdoc16;
	private String vreserve2;	
	private String vdef13;
	private String vreserve3;
	private String pk_defdoc11;	
	private String pk_defdoc9;	
	private String vdef11;
	private UFDouble nreserve10;
	private String pk_defdoc14;
	private String pk_defdoc20;	
	private String pk_defdoc4;	
	private String vdef3;	
	private String vdef12;
	private String vdef6;	
	private UFDouble nreserve6;
	private String pk_defdoc1;

	private Integer dr;
	private UFDateTime ts;


	public static final String PK_DEFDOC19 = "pk_defdoc19";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_DEFDOC10 = "pk_defdoc10";
	public static final String VDEF9 = "vdef9";
	public static final String VDEF10 = "vdef10";
	public static final String IMONTH = "imonth";
	public static final String CACCPERIODSCHEMEID = "caccperiodschemeid";
	public static final String PK_DEFDOC18 = "pk_defdoc18";
	public static final String CAPPLYDEPTID = "capplydeptid";
	public static final String VDEF15 = "vdef15";
	public static final String PK_DEFDOC8 = "pk_defdoc8";
	public static final String DBILLDATE = "dbilldate";
	public static final String CREQWAREHOUSEID = "creqwarehouseid";
	public static final String IYEAR = "iyear";
	public static final String VDEF14 = "vdef14";
	public static final String PK_DEFDOC5 = "pk_defdoc5";
	public static final String VRESERVE1 = "vreserve1";
	public static final String VDEF7 = "vdef7";
	public static final String DENDDATE = "denddate";
	public static final String PK_DEFDOC7 = "pk_defdoc7";
	public static final String PK_PLAN = "pk_plan";
	public static final String NRESERVE8 = "nreserve8";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF16 = "vdef16";
	public static final String VDEF5 = "vdef5";
	public static final String VMEMO = "vmemo";
	public static final String PK_DEFDOC12 = "pk_defdoc12";
	public static final String VDEF19 = "vdef19";
	public static final String VOPERATORID = "voperatorid";
	public static final String CSUPPLYDEPTID = "csupplydeptid";
	public static final String PK_DEFDOC13 = "pk_defdoc13";
	public static final String VBILLNO = "vbillno";
	public static final String PK_DEFDOC6 = "pk_defdoc6";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF18 = "vdef18";
	public static final String VRESERVE5 = "vreserve5";
	public static final String NRESERVE9 = "nreserve9";
	public static final String VDEF17 = "vdef17";
	public static final String PK_DEFDOC15 = "pk_defdoc15";
	public static final String CSUPPLYCORPID = "csupplycorpid";
	public static final String PK_DEFDOC2 = "pk_defdoc2";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF20 = "vdef20";
	public static final String VDEF8 = "vdef8";
	public static final String NRESERVE7 = "nreserve7";
	public static final String VAPPROVEID = "vapproveid";
	public static final String PK_DEFDOC3 = "pk_defdoc3";
	public static final String VRESERVE4 = "vreserve4";
	public static final String PK_DEFDOC17 = "pk_defdoc17";
	public static final String PK_DEFDOC16 = "pk_defdoc16";
	public static final String CINVCLASSID = "cinvclassid";
	public static final String VRESERVE2 = "vreserve2";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String CPLANPROJECTID = "cplanprojectid";
	public static final String VDEF13 = "vdef13";
	public static final String VRESERVE3 = "vreserve3";
	public static final String PK_DEFDOC11 = "pk_defdoc11";
	public static final String CAPPLYPSNID = "capplypsnid";
	public static final String PK_DEFDOC9 = "pk_defdoc9";
	public static final String DSTRATDATE = "dstratdate";
	public static final String VDEF11 = "vdef11";
	public static final String NRESERVE10 = "nreserve10";
	public static final String PK_DEFDOC14 = "pk_defdoc14";
	public static final String PK_DEFDOC20 = "pk_defdoc20";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String PK_DEFDOC4 = "pk_defdoc4";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VDEF3 = "vdef3";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF6 = "vdef6";
	public static final String NRESERVE6 = "nreserve6";
	public static final String PK_DEFDOC1 = "pk_defdoc1";
	public static final String CREQCALBODYID = "creqcalbodyid";

	/**
	 * 属性pk_defdoc19的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc19 () {
		return pk_defdoc19;
	}   
	/**
	 * 属性pk_defdoc19的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc19 String
	 */
	public void setPk_defdoc19 (String newPk_defdoc19 ) {
		this.pk_defdoc19 = newPk_defdoc19;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
		this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
		this.ts = newTs;
	} 	  
	/**
	 * 属性pk_defdoc10的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc10 () {
		return pk_defdoc10;
	}   
	/**
	 * 属性pk_defdoc10的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc10 String
	 */
	public void setPk_defdoc10 (String newPk_defdoc10 ) {
		this.pk_defdoc10 = newPk_defdoc10;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
		this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
		this.vdef10 = newVdef10;
	} 	  

	/**
	 * 属性caccperiodschemeid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCaccperiodschemeid () {
		return caccperiodschemeid;
	}   
	/**
	 * 属性caccperiodschemeid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCaccperiodschemeid String
	 */
	public void setCaccperiodschemeid (String newCaccperiodschemeid ) {
		this.caccperiodschemeid = newCaccperiodschemeid;
	} 	  
	/**
	 * 属性pk_defdoc18的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc18 () {
		return pk_defdoc18;
	}   
	/**
	 * 属性pk_defdoc18的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc18 String
	 */
	public void setPk_defdoc18 (String newPk_defdoc18 ) {
		this.pk_defdoc18 = newPk_defdoc18;
	} 	  
	/**
	 * 属性capplydeptid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCapplydeptid () {
		return capplydeptid;
	}   
	/**
	 * 属性capplydeptid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCapplydeptid String
	 */
	public void setCapplydeptid (String newCapplydeptid ) {
		this.capplydeptid = newCapplydeptid;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
		this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性pk_defdoc8的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc8 () {
		return pk_defdoc8;
	}   
	/**
	 * 属性pk_defdoc8的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc8 String
	 */
	public void setPk_defdoc8 (String newPk_defdoc8 ) {
		this.pk_defdoc8 = newPk_defdoc8;
	} 	  
	/**
	 * 属性dbilldate的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDate
	 */
	public UFDate getDbilldate () {
		return dbilldate;
	}   
	/**
	 * 属性dbilldate的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDbilldate UFDate
	 */
	public void setDbilldate (UFDate newDbilldate ) {
		this.dbilldate = newDbilldate;
	} 	  
	/**
	 * 属性creqwarehouseid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCreqwarehouseid () {
		return creqwarehouseid;
	}   
	/**
	 * 属性creqwarehouseid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCreqwarehouseid String
	 */
	public void setCreqwarehouseid (String newCreqwarehouseid ) {
		this.creqwarehouseid = newCreqwarehouseid;
	} 	  
	public String getCmonth() {
		return cmonth;
	}
	public void setCmonth(String cmonth) {
		this.cmonth = cmonth;
	}
	public String getCyear() {
		return cyear;
	}
	public void setCyear(String cyear) {
		this.cyear = cyear;
	}
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
		this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性pk_defdoc5的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc5 () {
		return pk_defdoc5;
	}   
	/**
	 * 属性pk_defdoc5的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc5 String
	 */
	public void setPk_defdoc5 (String newPk_defdoc5 ) {
		this.pk_defdoc5 = newPk_defdoc5;
	} 	  
	/**
	 * 属性vreserve1的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVreserve1 () {
		return vreserve1;
	}   
	/**
	 * 属性vreserve1的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVreserve1 String
	 */
	public void setVreserve1 (String newVreserve1 ) {
		this.vreserve1 = newVreserve1;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
		this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性denddate的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDate
	 */
	public UFDate getDenddate () {
		return denddate;
	}   
	/**
	 * 属性denddate的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDenddate UFDate
	 */
	public void setDenddate (UFDate newDenddate ) {
		this.denddate = newDenddate;
	} 	  
	/**
	 * 属性pk_defdoc7的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc7 () {
		return pk_defdoc7;
	}   
	/**
	 * 属性pk_defdoc7的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc7 String
	 */
	public void setPk_defdoc7 (String newPk_defdoc7 ) {
		this.pk_defdoc7 = newPk_defdoc7;
	} 	  
	/**
	 * 属性pk_plan的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_plan () {
		return pk_plan;
	}   
	/**
	 * 属性pk_plan的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_plan String
	 */
	public void setPk_plan (String newPk_plan ) {
		this.pk_plan = newPk_plan;
	} 	  
	/**
	 * 属性nreserve8的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public UFDouble getNreserve8 () {
		return nreserve8;
	}   
	/**
	 * 属性nreserve8的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newNreserve8 UFDouble
	 */
	public void setNreserve8 (UFDouble newNreserve8 ) {
		this.nreserve8 = newNreserve8;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
		this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
		this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
		this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
		this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性pk_defdoc12的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc12 () {
		return pk_defdoc12;
	}   
	/**
	 * 属性pk_defdoc12的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc12 String
	 */
	public void setPk_defdoc12 (String newPk_defdoc12 ) {
		this.pk_defdoc12 = newPk_defdoc12;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
		this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
		this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性csupplydeptid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCsupplydeptid () {
		return csupplydeptid;
	}   
	/**
	 * 属性csupplydeptid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCsupplydeptid String
	 */
	public void setCsupplydeptid (String newCsupplydeptid ) {
		this.csupplydeptid = newCsupplydeptid;
	} 	  
	/**
	 * 属性pk_defdoc13的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc13 () {
		return pk_defdoc13;
	}   
	/**
	 * 属性pk_defdoc13的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc13 String
	 */
	public void setPk_defdoc13 (String newPk_defdoc13 ) {
		this.pk_defdoc13 = newPk_defdoc13;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
		this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性pk_defdoc6的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc6 () {
		return pk_defdoc6;
	}   
	/**
	 * 属性pk_defdoc6的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc6 String
	 */
	public void setPk_defdoc6 (String newPk_defdoc6 ) {
		this.pk_defdoc6 = newPk_defdoc6;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
		this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
		this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性vreserve5的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVreserve5 () {
		return vreserve5;
	}   
	/**
	 * 属性vreserve5的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVreserve5 String
	 */
	public void setVreserve5 (String newVreserve5 ) {
		this.vreserve5 = newVreserve5;
	} 	  
	/**
	 * 属性nreserve9的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public UFDouble getNreserve9 () {
		return nreserve9;
	}   
	/**
	 * 属性nreserve9的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newNreserve9 UFDouble
	 */
	public void setNreserve9 (UFDouble newNreserve9 ) {
		this.nreserve9 = newNreserve9;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
		this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性pk_defdoc15的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc15 () {
		return pk_defdoc15;
	}   
	/**
	 * 属性pk_defdoc15的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc15 String
	 */
	public void setPk_defdoc15 (String newPk_defdoc15 ) {
		this.pk_defdoc15 = newPk_defdoc15;
	} 	  
	/**
	 * 属性csupplycorpid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCsupplycorpid () {
		return csupplycorpid;
	}   
	/**
	 * 属性csupplycorpid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCsupplycorpid String
	 */
	public void setCsupplycorpid (String newCsupplycorpid ) {
		this.csupplycorpid = newCsupplycorpid;
	} 	  
	/**
	 * 属性pk_defdoc2的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc2 () {
		return pk_defdoc2;
	}   
	/**
	 * 属性pk_defdoc2的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc2 String
	 */
	public void setPk_defdoc2 (String newPk_defdoc2 ) {
		this.pk_defdoc2 = newPk_defdoc2;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
		this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
		this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
		this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性nreserve7的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public UFDouble getNreserve7 () {
		return nreserve7;
	}   
	/**
	 * 属性nreserve7的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newNreserve7 UFDouble
	 */
	public void setNreserve7 (UFDouble newNreserve7 ) {
		this.nreserve7 = newNreserve7;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
		this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性pk_defdoc3的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc3 () {
		return pk_defdoc3;
	}   
	/**
	 * 属性pk_defdoc3的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc3 String
	 */
	public void setPk_defdoc3 (String newPk_defdoc3 ) {
		this.pk_defdoc3 = newPk_defdoc3;
	} 	  
	/**
	 * 属性vreserve4的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVreserve4 () {
		return vreserve4;
	}   
	/**
	 * 属性vreserve4的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVreserve4 String
	 */
	public void setVreserve4 (String newVreserve4 ) {
		this.vreserve4 = newVreserve4;
	} 	  
	/**
	 * 属性pk_defdoc17的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc17 () {
		return pk_defdoc17;
	}   
	/**
	 * 属性pk_defdoc17的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc17 String
	 */
	public void setPk_defdoc17 (String newPk_defdoc17 ) {
		this.pk_defdoc17 = newPk_defdoc17;
	} 	  
	/**
	 * 属性pk_defdoc16的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc16 () {
		return pk_defdoc16;
	}   
	/**
	 * 属性pk_defdoc16的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc16 String
	 */
	public void setPk_defdoc16 (String newPk_defdoc16 ) {
		this.pk_defdoc16 = newPk_defdoc16;
	} 	  
	/**
	 * 属性cinvclassid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCinvclassid () {
		return cinvclassid;
	}   
	/**
	 * 属性cinvclassid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCinvclassid String
	 */
	public void setCinvclassid (String newCinvclassid ) {
		this.cinvclassid = newCinvclassid;
	} 	  
	/**
	 * 属性vreserve2的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVreserve2 () {
		return vreserve2;
	}   
	/**
	 * 属性vreserve2的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVreserve2 String
	 */
	public void setVreserve2 (String newVreserve2 ) {
		this.vreserve2 = newVreserve2;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
		this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性cplanprojectid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCplanprojectid () {
		return cplanprojectid;
	}   
	/**
	 * 属性cplanprojectid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCplanprojectid String
	 */
	public void setCplanprojectid (String newCplanprojectid ) {
		this.cplanprojectid = newCplanprojectid;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
		this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性vreserve3的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVreserve3 () {
		return vreserve3;
	}   
	/**
	 * 属性vreserve3的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVreserve3 String
	 */
	public void setVreserve3 (String newVreserve3 ) {
		this.vreserve3 = newVreserve3;
	} 	  
	/**
	 * 属性pk_defdoc11的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc11 () {
		return pk_defdoc11;
	}   
	/**
	 * 属性pk_defdoc11的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc11 String
	 */
	public void setPk_defdoc11 (String newPk_defdoc11 ) {
		this.pk_defdoc11 = newPk_defdoc11;
	} 	  
	/**
	 * 属性capplypsnid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCapplypsnid () {
		return capplypsnid;
	}   
	/**
	 * 属性capplypsnid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCapplypsnid String
	 */
	public void setCapplypsnid (String newCapplypsnid ) {
		this.capplypsnid = newCapplypsnid;
	} 	  
	/**
	 * 属性pk_defdoc9的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc9 () {
		return pk_defdoc9;
	}   
	/**
	 * 属性pk_defdoc9的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc9 String
	 */
	public void setPk_defdoc9 (String newPk_defdoc9 ) {
		this.pk_defdoc9 = newPk_defdoc9;
	} 	  
	/**
	 * 属性dstratdate的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDate
	 */
	public UFDate getDstratdate () {
		return dstratdate;
	}   
	/**
	 * 属性dstratdate的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDstratdate UFDate
	 */
	public void setDstratdate (UFDate newDstratdate ) {
		this.dstratdate = newDstratdate;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
		this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性nreserve10的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public UFDouble getNreserve10 () {
		return nreserve10;
	}   
	/**
	 * 属性nreserve10的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newNreserve10 UFDouble
	 */
	public void setNreserve10 (UFDouble newNreserve10 ) {
		this.nreserve10 = newNreserve10;
	} 	  
	/**
	 * 属性pk_defdoc14的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc14 () {
		return pk_defdoc14;
	}   
	/**
	 * 属性pk_defdoc14的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc14 String
	 */
	public void setPk_defdoc14 (String newPk_defdoc14 ) {
		this.pk_defdoc14 = newPk_defdoc14;
	} 	  
	/**
	 * 属性pk_defdoc20的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc20 () {
		return pk_defdoc20;
	}   
	/**
	 * 属性pk_defdoc20的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc20 String
	 */
	public void setPk_defdoc20 (String newPk_defdoc20 ) {
		this.pk_defdoc20 = newPk_defdoc20;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
		this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性pk_defdoc4的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc4 () {
		return pk_defdoc4;
	}   
	/**
	 * 属性pk_defdoc4的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc4 String
	 */
	public void setPk_defdoc4 (String newPk_defdoc4 ) {
		this.pk_defdoc4 = newPk_defdoc4;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
		this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
		this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
		this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
		this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
		this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
		this.dr = newDr;
	} 	  
	/**
	 * 属性nreserve6的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return UFDouble
	 */
	public UFDouble getNreserve6 () {
		return nreserve6;
	}   
	/**
	 * 属性nreserve6的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newNreserve6 UFDouble
	 */
	public void setNreserve6 (UFDouble newNreserve6 ) {
		this.nreserve6 = newNreserve6;
	} 	  
	/**
	 * 属性pk_defdoc1的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getPk_defdoc1 () {
		return pk_defdoc1;
	}   
	/**
	 * 属性pk_defdoc1的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newPk_defdoc1 String
	 */
	public void setPk_defdoc1 (String newPk_defdoc1 ) {
		this.pk_defdoc1 = newPk_defdoc1;
	} 	  
	/**
	 * 属性creqcalbodyid的Getter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @return String
	 */
	public String getCreqcalbodyid () {
		return creqcalbodyid;
	}   
	/**
	 * 属性creqcalbodyid的Setter方法.
	 * 创建日期:2011-11-01 10:37:18
	 * @param newCreqcalbodyid String
	 */
	public void setCreqcalbodyid (String newCreqcalbodyid ) {
		this.creqcalbodyid = newCreqcalbodyid;
	} 	  

	/**
	 * <p>取得父VO主键字段.
	 * <p>
	 * 创建日期:2011-11-01 10:37:18
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}   

	/**
	 * <p>取得表主键.
	 * <p>
	 * 创建日期:2011-11-01 10:37:18
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_plan";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-11-01 10:37:18
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "HG_PLAN";
	}    

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2011-11-01 10:37:18
	 */
	public PlanVO() {
		super();	
	}
	public String getVapprovenote() {
		return vapprovenote;
	}
	public void setVapprovenote(String vapprovenote) {
		this.vapprovenote = vapprovenote;
	}
	public UFBoolean getFisclose() {
		return fisclose;
	}
	public void setFisclose(UFBoolean fisclose) {
		this.fisclose = fisclose;
	}  

	/**
	 * 
	 * @author zhf
	 * @说明：（鹤岗矿业）
	 * 2011-1-26下午12:50:43
	 * @throws ValidationException
	 */
	public void validata() throws ValidationException{

		if(PuPubVO.getString_TrimZeroLenAsNull(getCapplydeptid())==null){
			throw new ValidationException("申请部门不能为空");
		}
		//		if(PuPubVO.getString_TrimZeroLenAsNull(getCapplypsnid())==null){
		//			throw new ValidationException("申请人不能为空");
		//		}
		//
		//		if(PuPubVO.getString_TrimZeroLenAsNull(getCinvclassid())==null){
		//			throw new ValidationException("申请物资类别不能为空");
		//		}

		if(PuPubVO.getString_TrimZeroLenAsNull(getCaccperiodschemeid())==null){
			throw new ValidationException("会计期间方案不能为空");
		}

		if(PuPubVO.getString_TrimZeroLenAsNull(getCsupplycorpid())==null){
			throw new ValidationException("供货单位不能为空");
		}
		//		if(PuPubVO.getString_TrimZeroLenAsNull(getCsupplydeptid())==null){
		//			throw new ValidationException("供货部门不能为空");
		//		}
		if(PuPubVO.getString_TrimZeroLenAsNull(getPk_corp())==null){
			throw new ValidationException("申请单位不能为空");
		}

		if(PuPubVO.getString_TrimZeroLenAsNull(getPk_billtype())==null){
			throw new ValidationException("单据类型不能为空");
		}

		if(HgPubConst.PLAN_MONTH_BILLTYPE.equalsIgnoreCase(getPk_billtype())){
			if(PuPubVO.getString_TrimZeroLenAsNull(getCyear())==null){
				throw new ValidationException("年度不能为空");
			}
			if(PuPubVO.getString_TrimZeroLenAsNull(getCmonth())==null){
				throw new ValidationException("月份不能为空");
			}
		}else if(HgPubConst.PLAN_TEMP_BILLTYPE.equalsIgnoreCase(getPk_billtype())){

		}else if(HgPubConst.PLAN_MNY_BILLTYPE.equalsIgnoreCase(getPk_billtype())){
			if(PuPubVO.getString_TrimZeroLenAsNull(getCplanprojectid())==null)
				throw new ValidationException("计划项目不能为空");
		}else if(HgPubConst.PLAN_YEAR_BILLTYPE.equalsIgnoreCase(getPk_billtype())){
			if(PuPubVO.getString_TrimZeroLenAsNull(getCyear())==null){
				throw new ValidationException("年度不能为空");
			}
		}

		if(PuPubVO.getString_TrimZeroLenAsNull(getCsupplydeptid())!=null
				&&PuPubVO.getString_TrimZeroLenAsNull(getCapplydeptid())!=null){
			if(getCsupplydeptid().equalsIgnoreCase(getCapplydeptid())){
				throw new ValidationException("申请部门与供货部门不能为同一个");
			}
		}

	}
	public String getCsourcebillno() {
		return csourcebillno;
	}
	public void setCsourcebillno(String csourcebillno) {
		this.csourcebillno = csourcebillno;
	}
	public UFBoolean getFisself() {
		return fisself;
	}
	public void setFisself(UFBoolean fisself) {
		this.fisself = fisself;
	}
	public String getPk_busitype() {
		return pk_busitype;
	}
	public void setPk_busitype(String pk_busitype) {
		this.pk_busitype = pk_busitype;
	}
} 
