/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wds.ie.loadcost;

import java.util.ArrayList;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2010-12-23
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class TbHandlecostsVO extends SuperVO {

	public String wd_document3;
	public String hc_customize3;
	public String hc_customize5;
	public String hc_customize8;
	public String wt_pk;
	public String wd_document;
	public String hc_customize2;
	public String wd_document2;
	public Integer dr;
	public String hc_customize9;
	public String hc_pk;
	public String hc_customize7;
	public String hc_code;
	public String hc_customize1;
	public UFTime ts;
	public UFDouble hc_totalcost;
	public String nvote;
	public String hc_handlingbatch;
	public String hc_customize6;
	public String hc_customize4;
	public UFDate dbilldate;// 单据日期
	public Integer dbilltype;// 单据类型
	public UFDouble hc_addcost;// 附加费
	public UFDouble hc_avgcost;// 平均费用
	public Integer hc_mannum;// 装卸人数
	public Integer handtype;// 装卸类型
	public String csourcebillhid;//来源单据表头主键

	public static final String CSOURCEBILLHID="csourcebillhid";
	public static final String HANDTYPE = "handtype";
	public static final String HC_MANNUM = "hc_mannum";
	public static final String HC_AVGCOST = "hc_avgcost";
	public static final String HC_ADDCOST = "hc_addcost";
	public static final String DBILLTYPE = "dbilltype";
	public static final String DBILLDATE = "dbilldate";
	public static final String WD_DOCUMENT3 = "wd_document3";
	public static final String HC_CUSTOMIZE3 = "hc_customize3";
	public static final String HC_CUSTOMIZE5 = "hc_customize5";
	public static final String HC_CUSTOMIZE8 = "hc_customize8";
	public static final String WT_PK = "wt_pk";
	public static final String WD_DOCUMENT = "wd_document";
	public static final String HC_CUSTOMIZE2 = "hc_customize2";
	public static final String WD_DOCUMENT2 = "wd_document2";
	public static final String DR = "dr";
	public static final String HC_CUSTOMIZE9 = "hc_customize9";
	public static final String HC_PK = "hc_pk";
	public static final String HC_CUSTOMIZE7 = "hc_customize7";
	public static final String HC_CODE = "hc_code";
	public static final String HC_CUSTOMIZE1 = "hc_customize1";
	public static final String TS = "ts";
	public static final String HC_TOTALCOST = "hc_totalcost";
	public static final String NVOTE = "nvote";
	public static final String HC_HANDLINGBATCH = "hc_handlingbatch";
	public static final String HC_CUSTOMIZE6 = "hc_customize6";
	public static final String HC_CUSTOMIZE4 = "hc_customize4";

	/**
	 * 属性wd_document3的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getWd_document3() {
		return wd_document3;
	}

	/**
	 * 属性wd_document3的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newWd_document3
	 *            String
	 */
	public void setWd_document3(String newWd_document3) {

		wd_document3 = newWd_document3;
	}

	/**
	 * 属性hc_customize3的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize3() {
		return hc_customize3;
	}

	/**
	 * 属性hc_customize3的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize3
	 *            String
	 */
	public void setHc_customize3(String newHc_customize3) {

		hc_customize3 = newHc_customize3;
	}

	/**
	 * 属性hc_customize5的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize5() {
		return hc_customize5;
	}

	/**
	 * 属性hc_customize5的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize5
	 *            String
	 */
	public void setHc_customize5(String newHc_customize5) {

		hc_customize5 = newHc_customize5;
	}

	/**
	 * 属性hc_customize8的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize8() {
		return hc_customize8;
	}

	/**
	 * 属性hc_customize8的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize8
	 *            String
	 */
	public void setHc_customize8(String newHc_customize8) {

		hc_customize8 = newHc_customize8;
	}

	/**
	 * 属性wt_pk的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getWt_pk() {
		return wt_pk;
	}

	/**
	 * 属性wt_pk的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newWt_pk
	 *            String
	 */
	public void setWt_pk(String newWt_pk) {

		wt_pk = newWt_pk;
	}

	/**
	 * 属性wd_document的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getWd_document() {
		return wd_document;
	}

	/**
	 * 属性wd_document的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newWd_document
	 *            String
	 */
	public void setWd_document(String newWd_document) {

		wd_document = newWd_document;
	}

	/**
	 * 属性hc_customize2的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize2() {
		return hc_customize2;
	}

	/**
	 * 属性hc_customize2的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize2
	 *            String
	 */
	public void setHc_customize2(String newHc_customize2) {

		hc_customize2 = newHc_customize2;
	}

	/**
	 * 属性wd_document2的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getWd_document2() {
		return wd_document2;
	}

	/**
	 * 属性wd_document2的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newWd_document2
	 *            String
	 */
	public void setWd_document2(String newWd_document2) {

		wd_document2 = newWd_document2;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性hc_customize9的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize9() {
		return hc_customize9;
	}

	/**
	 * 属性hc_customize9的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize9
	 *            String
	 */
	public void setHc_customize9(String newHc_customize9) {

		hc_customize9 = newHc_customize9;
	}

	/**
	 * 属性hc_pk的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_pk() {
		return hc_pk;
	}

	/**
	 * 属性hc_pk的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_pk
	 *            String
	 */
	public void setHc_pk(String newHc_pk) {

		hc_pk = newHc_pk;
	}

	/**
	 * 属性hc_customize7的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize7() {
		return hc_customize7;
	}

	/**
	 * 属性hc_customize7的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize7
	 *            String
	 */
	public void setHc_customize7(String newHc_customize7) {

		hc_customize7 = newHc_customize7;
	}

	/**
	 * 属性hc_code的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_code() {
		return hc_code;
	}

	/**
	 * 属性hc_code的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_code
	 *            String
	 */
	public void setHc_code(String newHc_code) {

		hc_code = newHc_code;
	}

	/**
	 * 属性hc_customize1的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize1() {
		return hc_customize1;
	}

	/**
	 * 属性hc_customize1的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize1
	 *            String
	 */
	public void setHc_customize1(String newHc_customize1) {

		hc_customize1 = newHc_customize1;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return UFDateTime
	 */
	public UFTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newTs
	 *            UFDateTime
	 */
	public void setTs(UFTime newTs) {

		ts = newTs;
	}

	/**
	 * 属性hc_totalcost的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return UFDouble
	 */
	public UFDouble getHc_totalcost() {
		return hc_totalcost;
	}

	/**
	 * 属性hc_totalcost的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_totalcost
	 *            UFDouble
	 */
	public void setHc_totalcost(UFDouble newHc_totalcost) {

		hc_totalcost = newHc_totalcost;
	}

	/**
	 * 属性nvote的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getNvote() {
		return nvote;
	}

	/**
	 * 属性nvote的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newNvote
	 *            String
	 */
	public void setNvote(String newNvote) {

		nvote = newNvote;
	}

	/**
	 * 属性hc_handlingbatch的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_handlingbatch() {
		return hc_handlingbatch;
	}

	/**
	 * 属性hc_handlingbatch的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_handlingbatch
	 *            String
	 */
	public void setHc_handlingbatch(String newHc_handlingbatch) {

		hc_handlingbatch = newHc_handlingbatch;
	}

	/**
	 * 属性hc_customize6的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize6() {
		return hc_customize6;
	}

	/**
	 * 属性hc_customize6的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize6
	 *            String
	 */
	public void setHc_customize6(String newHc_customize6) {

		hc_customize6 = newHc_customize6;
	}

	/**
	 * 属性hc_customize4的Getter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getHc_customize4() {
		return hc_customize4;
	}

	/**
	 * 属性hc_customize4的Setter方法.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_customize4
	 *            String
	 */
	public void setHc_customize4(String newHc_customize4) {

		hc_customize4 = newHc_customize4;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		if (hc_pk == null) {
			errFields.add(new String("hc_pk"));
		}

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2010-12-23
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2010-12-23
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "hc_pk";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2010-12-23
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "tb_handlecosts";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2010-12-23
	 */
	public TbHandlecostsVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_pk
	 *            主键值
	 */
	public TbHandlecostsVO(String newHc_pk) {

		// 为主键字段赋值:
		hc_pk = newHc_pk;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return hc_pk;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @param newHc_pk
	 *            String
	 */
	public void setPrimaryKey(String newHc_pk) {

		hc_pk = newHc_pk;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2010-12-23
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "tb_handlecosts";

	}

	public UFDate getDbilldate() {
		return dbilldate;
	}

	public void setDbilldate(UFDate dbilldate) {
		this.dbilldate = dbilldate;
	}

	public Integer getDbilltype() {
		return dbilltype;
	}

	public void setDbilltype(Integer dbilltype) {
		this.dbilltype = dbilltype;
	}

	public UFDouble getHc_addcost() {
		return hc_addcost;
	}

	public void setHc_addcost(UFDouble hc_addcost) {
		this.hc_addcost = hc_addcost;
	}

	public UFDouble getHc_avgcost() {
		return hc_avgcost;
	}

	public void setHc_avgcost(UFDouble hc_avgcost) {
		this.hc_avgcost = hc_avgcost;
	}

	public Integer getHc_mannum() {
		return hc_mannum;
	}

	public void setHc_mannum(Integer hc_mannum) {
		this.hc_mannum = hc_mannum;
	}

	public Integer getHandtype() {
		return handtype;
	}

	public void setHandtype(Integer handtype) {
		this.handtype = handtype;
	}

	public String getCsourcebillhid() {
		return csourcebillhid;
	}

	public void setCsourcebillhid(String csourcebillhid) {
		this.csourcebillhid = csourcebillhid;
	}
}
