  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ic.pub;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2010-7-12
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class IcGeneralHVO extends SuperVO {
           
             public String pk_corp;
             public String vuserdef9;
             public String ccustomerid;
             public String cdilivertypeid;
             public UFBoolean bdirecttranflag;
             public String csettlepathid;
             public String vuserdef3;
             public Integer dr;
             public UFBoolean bdelivedtorm;
             public String cauditorid;
             public String pk_measware;
             public String coutcalbodyid;
             public String cwhsmanagerid;
             public String coperatorid;
             public Integer fbillflag;
             public UFTime ts;
             public String pk_defdoc11;
             public Integer iprintcount;
             public String vuserdef14;
             public String vuserdef20;
             public UFBoolean freplenishflag;
             public String pk_defdoc10;
             public String pk_defdoc6;
             public UFDateTime tmaketime;
             public String cbiztype;
             public String pk_defdoc20;
             public String cwastewarehouseid;
             public String pk_cubasdoc;
             public String pk_defdoc3;
             public String pk_defdoc12;
             public UFBoolean boutretflag;
             public String vuserdef10;
             public String cothercalbodyid;
             public String pk_defdoc2;
             public String vdiliveraddress;
             public String pk_defdoc7;
             public String pk_defdoc17;
             public UFDouble ndiscountmny;
             public String pk_cubasdocc;
             public String pk_defdoc15;
             public String vbillcode;
             public String vuserdef12;
             public String cinventoryid;
             public String pk_defdoc16;
             public UFDate dauditdate;
             public String pk_defdoc13;
             public String vuserdef11;
             public String vuserdef15;
             public String pk_purcorp;
             public String vuserdef17;
             public String cothercorpid;
             public String cdptid;
             public String cdispatcherid;
             public String cendreportid;
             public String cbizid;
             public String pk_defdoc18;
             public String vheadnote2;
             public String cbilltypecode;
             public String pk_defdoc9;
             public UFDateTime tlastmoditime;
             public String vuserdef1;
             public String pk_calbody;
             public String clastmodiid;
             public String cproviderid;
             public String pk_defdoc1;
             public String cotherwhid;
             public UFDate dbilldate;
             public String pk_defdoc19;
             public String pk_defdoc4;
             public Integer fspecialflag;
             public String pk_defdoc5;
             public String vuserdef2;
             public String cgeneralhid;
             public String vuserdef5;
             public String vuserdef16;
             public String vnote;
             public String vuserdef8;
             public String coutcorpid;
             public String vuserdef4;
             public String cregister;
             public String pk_defdoc8;
             public UFDate daccountdate;
             public String vuserdef18;
             public String vuserdef7;
             public Integer fallocflag;
             public String pk_defdoc14;
             public UFDouble nnetmny;
             public UFDateTime taccounttime;
             public String vuserdef19;
             public String cwarehouseid;
             public String vuserdef13;
             public String vuserdef6;
            
             public static final String  PK_CORP="pk_corp";   
             public static final String  VUSERDEF9="vuserdef9";   
             public static final String  CCUSTOMERID="ccustomerid";   
             public static final String  CDILIVERTYPEID="cdilivertypeid";   
             public static final String  BDIRECTTRANFLAG="bdirecttranflag";   
             public static final String  CSETTLEPATHID="csettlepathid";   
             public static final String  VUSERDEF3="vuserdef3";   
             public static final String  DR="dr";   
             public static final String  BDELIVEDTORM="bdelivedtorm";   
             public static final String  CAUDITORID="cauditorid";   
             public static final String  PK_MEASWARE="pk_measware";   
             public static final String  COUTCALBODYID="coutcalbodyid";   
             public static final String  CWHSMANAGERID="cwhsmanagerid";   
             public static final String  COPERATORID="coperatorid";   
             public static final String  FBILLFLAG="fbillflag";   
             public static final String  TS="ts";   
             public static final String  PK_DEFDOC11="pk_defdoc11";   
             public static final String  IPRINTCOUNT="iprintcount";   
             public static final String  VUSERDEF14="vuserdef14";   
             public static final String  VUSERDEF20="vuserdef20";   
             public static final String  FREPLENISHFLAG="freplenishflag";   
             public static final String  PK_DEFDOC10="pk_defdoc10";   
             public static final String  PK_DEFDOC6="pk_defdoc6";   
             public static final String  TMAKETIME="tmaketime";   
             public static final String  CBIZTYPE="cbiztype";   
             public static final String  PK_DEFDOC20="pk_defdoc20";   
             public static final String  CWASTEWAREHOUSEID="cwastewarehouseid";   
             public static final String  PK_CUBASDOC="pk_cubasdoc";   
             public static final String  PK_DEFDOC3="pk_defdoc3";   
             public static final String  PK_DEFDOC12="pk_defdoc12";   
             public static final String  BOUTRETFLAG="boutretflag";   
             public static final String  VUSERDEF10="vuserdef10";   
             public static final String  COTHERCALBODYID="cothercalbodyid";   
             public static final String  PK_DEFDOC2="pk_defdoc2";   
             public static final String  VDILIVERADDRESS="vdiliveraddress";   
             public static final String  PK_DEFDOC7="pk_defdoc7";   
             public static final String  PK_DEFDOC17="pk_defdoc17";   
             public static final String  NDISCOUNTMNY="ndiscountmny";   
             public static final String  PK_CUBASDOCC="pk_cubasdocc";   
             public static final String  PK_DEFDOC15="pk_defdoc15";   
             public static final String  VBILLCODE="vbillcode";   
             public static final String  VUSERDEF12="vuserdef12";   
             public static final String  CINVENTORYID="cinventoryid";   
             public static final String  PK_DEFDOC16="pk_defdoc16";   
             public static final String  DAUDITDATE="dauditdate";   
             public static final String  PK_DEFDOC13="pk_defdoc13";   
             public static final String  VUSERDEF11="vuserdef11";   
             public static final String  VUSERDEF15="vuserdef15";   
             public static final String  PK_PURCORP="pk_purcorp";   
             public static final String  VUSERDEF17="vuserdef17";   
             public static final String  COTHERCORPID="cothercorpid";   
             public static final String  CDPTID="cdptid";   
             public static final String  CDISPATCHERID="cdispatcherid";   
             public static final String  CENDREPORTID="cendreportid";   
             public static final String  CBIZID="cbizid";   
             public static final String  PK_DEFDOC18="pk_defdoc18";   
             public static final String  VHEADNOTE2="vheadnote2";   
             public static final String  CBILLTYPECODE="cbilltypecode";   
             public static final String  PK_DEFDOC9="pk_defdoc9";   
             public static final String  TLASTMODITIME="tlastmoditime";   
             public static final String  VUSERDEF1="vuserdef1";   
             public static final String  PK_CALBODY="pk_calbody";   
             public static final String  CLASTMODIID="clastmodiid";   
             public static final String  CPROVIDERID="cproviderid";   
             public static final String  PK_DEFDOC1="pk_defdoc1";   
             public static final String  COTHERWHID="cotherwhid";   
             public static final String  DBILLDATE="dbilldate";   
             public static final String  PK_DEFDOC19="pk_defdoc19";   
             public static final String  PK_DEFDOC4="pk_defdoc4";   
             public static final String  FSPECIALFLAG="fspecialflag";   
             public static final String  PK_DEFDOC5="pk_defdoc5";   
             public static final String  VUSERDEF2="vuserdef2";   
             public static final String  CGENERALHID="cgeneralhid";   
             public static final String  VUSERDEF5="vuserdef5";   
             public static final String  VUSERDEF16="vuserdef16";   
             public static final String  VNOTE="vnote";   
             public static final String  VUSERDEF8="vuserdef8";   
             public static final String  COUTCORPID="coutcorpid";   
             public static final String  VUSERDEF4="vuserdef4";   
             public static final String  CREGISTER="cregister";   
             public static final String  PK_DEFDOC8="pk_defdoc8";   
             public static final String  DACCOUNTDATE="daccountdate";   
             public static final String  VUSERDEF18="vuserdef18";   
             public static final String  VUSERDEF7="vuserdef7";   
             public static final String  FALLOCFLAG="fallocflag";   
             public static final String  PK_DEFDOC14="pk_defdoc14";   
             public static final String  NNETMNY="nnetmny";   
             public static final String  TACCOUNTTIME="taccounttime";   
             public static final String  VUSERDEF19="vuserdef19";   
             public static final String  CWAREHOUSEID="cwarehouseid";   
             public static final String  VUSERDEF13="vuserdef13";   
             public static final String  VUSERDEF6="vuserdef6";   
      
    
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性vuserdef9的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef9() {
		 return vuserdef9;
	  }   
	  
     /**
	   * 属性vuserdef9的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef9 String
	   */
	public void setVuserdef9(String newVuserdef9) {
		
		vuserdef9 = newVuserdef9;
	 } 	  
       
        /**
	   * 属性ccustomerid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCcustomerid() {
		 return ccustomerid;
	  }   
	  
     /**
	   * 属性ccustomerid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCcustomerid String
	   */
	public void setCcustomerid(String newCcustomerid) {
		
		ccustomerid = newCcustomerid;
	 } 	  
       
        /**
	   * 属性cdilivertypeid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCdilivertypeid() {
		 return cdilivertypeid;
	  }   
	  
     /**
	   * 属性cdilivertypeid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCdilivertypeid String
	   */
	public void setCdilivertypeid(String newCdilivertypeid) {
		
		cdilivertypeid = newCdilivertypeid;
	 } 	  
       
        /**
	   * 属性bdirecttranflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFBoolean
	   */
	 public UFBoolean getBdirecttranflag() {
		 return bdirecttranflag;
	  }   
	  
     /**
	   * 属性bdirecttranflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newBdirecttranflag UFBoolean
	   */
	public void setBdirecttranflag(UFBoolean newBdirecttranflag) {
		
		bdirecttranflag = newBdirecttranflag;
	 } 	  
       
        /**
	   * 属性csettlepathid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCsettlepathid() {
		 return csettlepathid;
	  }   
	  
     /**
	   * 属性csettlepathid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCsettlepathid String
	   */
	public void setCsettlepathid(String newCsettlepathid) {
		
		csettlepathid = newCsettlepathid;
	 } 	  
       
        /**
	   * 属性vuserdef3的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef3() {
		 return vuserdef3;
	  }   
	  
     /**
	   * 属性vuserdef3的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef3 String
	   */
	public void setVuserdef3(String newVuserdef3) {
		
		vuserdef3 = newVuserdef3;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性bdelivedtorm的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFBoolean
	   */
	 public UFBoolean getBdelivedtorm() {
		 return bdelivedtorm;
	  }   
	  
     /**
	   * 属性bdelivedtorm的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newBdelivedtorm UFBoolean
	   */
	public void setBdelivedtorm(UFBoolean newBdelivedtorm) {
		
		bdelivedtorm = newBdelivedtorm;
	 } 	  
       
        /**
	   * 属性cauditorid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCauditorid() {
		 return cauditorid;
	  }   
	  
     /**
	   * 属性cauditorid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCauditorid String
	   */
	public void setCauditorid(String newCauditorid) {
		
		cauditorid = newCauditorid;
	 } 	  
       
        /**
	   * 属性pk_measware的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_measware() {
		 return pk_measware;
	  }   
	  
     /**
	   * 属性pk_measware的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_measware String
	   */
	public void setPk_measware(String newPk_measware) {
		
		pk_measware = newPk_measware;
	 } 	  
       
        /**
	   * 属性coutcalbodyid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCoutcalbodyid() {
		 return coutcalbodyid;
	  }   
	  
     /**
	   * 属性coutcalbodyid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCoutcalbodyid String
	   */
	public void setCoutcalbodyid(String newCoutcalbodyid) {
		
		coutcalbodyid = newCoutcalbodyid;
	 } 	  
       
        /**
	   * 属性cwhsmanagerid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCwhsmanagerid() {
		 return cwhsmanagerid;
	  }   
	  
     /**
	   * 属性cwhsmanagerid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCwhsmanagerid String
	   */
	public void setCwhsmanagerid(String newCwhsmanagerid) {
		
		cwhsmanagerid = newCwhsmanagerid;
	 } 	  
       
        /**
	   * 属性coperatorid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCoperatorid() {
		 return coperatorid;
	  }   
	  
     /**
	   * 属性coperatorid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCoperatorid String
	   */
	public void setCoperatorid(String newCoperatorid) {
		
		coperatorid = newCoperatorid;
	 } 	  
       
        /**
	   * 属性fbillflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return Integer
	   */
	 public Integer getFbillflag() {
		 return fbillflag;
	  }   
	  
     /**
	   * 属性fbillflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newFbillflag Integer
	   */
	public void setFbillflag(Integer newFbillflag) {
		
		fbillflag = newFbillflag;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDateTime
	   */
	 public UFTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newTs UFDateTime
	   */
	public void setTs(UFTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性pk_defdoc11的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc11() {
		 return pk_defdoc11;
	  }   
	  
     /**
	   * 属性pk_defdoc11的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc11 String
	   */
	public void setPk_defdoc11(String newPk_defdoc11) {
		
		pk_defdoc11 = newPk_defdoc11;
	 } 	  
       
        /**
	   * 属性iprintcount的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return Integer
	   */
	 public Integer getIprintcount() {
		 return iprintcount;
	  }   
	  
     /**
	   * 属性iprintcount的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newIprintcount Integer
	   */
	public void setIprintcount(Integer newIprintcount) {
		
		iprintcount = newIprintcount;
	 } 	  
       
        /**
	   * 属性vuserdef14的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef14() {
		 return vuserdef14;
	  }   
	  
     /**
	   * 属性vuserdef14的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef14 String
	   */
	public void setVuserdef14(String newVuserdef14) {
		
		vuserdef14 = newVuserdef14;
	 } 	  
       
        /**
	   * 属性vuserdef20的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef20() {
		 return vuserdef20;
	  }   
	  
     /**
	   * 属性vuserdef20的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef20 String
	   */
	public void setVuserdef20(String newVuserdef20) {
		
		vuserdef20 = newVuserdef20;
	 } 	  
       
        /**
	   * 属性freplenishflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFBoolean
	   */
	 public UFBoolean getFreplenishflag() {
		 return freplenishflag;
	  }   
	  
     /**
	   * 属性freplenishflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newFreplenishflag UFBoolean
	   */
	public void setFreplenishflag(UFBoolean newFreplenishflag) {
		
		freplenishflag = newFreplenishflag;
	 } 	  
       
        /**
	   * 属性pk_defdoc10的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc10() {
		 return pk_defdoc10;
	  }   
	  
     /**
	   * 属性pk_defdoc10的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc10 String
	   */
	public void setPk_defdoc10(String newPk_defdoc10) {
		
		pk_defdoc10 = newPk_defdoc10;
	 } 	  
       
        /**
	   * 属性pk_defdoc6的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc6() {
		 return pk_defdoc6;
	  }   
	  
     /**
	   * 属性pk_defdoc6的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc6 String
	   */
	public void setPk_defdoc6(String newPk_defdoc6) {
		
		pk_defdoc6 = newPk_defdoc6;
	 } 	  
       
        /**
	   * 属性tmaketime的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDateTime
	   */
	 public UFDateTime getTmaketime() {
		 return tmaketime;
	  }   
	  
     /**
	   * 属性tmaketime的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newTmaketime UFDateTime
	   */
	public void setTmaketime(UFDateTime newTmaketime) {
		
		tmaketime = newTmaketime;
	 } 	  
       
        /**
	   * 属性cbiztype的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCbiztype() {
		 return cbiztype;
	  }   
	  
     /**
	   * 属性cbiztype的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCbiztype String
	   */
	public void setCbiztype(String newCbiztype) {
		
		cbiztype = newCbiztype;
	 } 	  
       
        /**
	   * 属性pk_defdoc20的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc20() {
		 return pk_defdoc20;
	  }   
	  
     /**
	   * 属性pk_defdoc20的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc20 String
	   */
	public void setPk_defdoc20(String newPk_defdoc20) {
		
		pk_defdoc20 = newPk_defdoc20;
	 } 	  
       
        /**
	   * 属性cwastewarehouseid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCwastewarehouseid() {
		 return cwastewarehouseid;
	  }   
	  
     /**
	   * 属性cwastewarehouseid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCwastewarehouseid String
	   */
	public void setCwastewarehouseid(String newCwastewarehouseid) {
		
		cwastewarehouseid = newCwastewarehouseid;
	 } 	  
       
        /**
	   * 属性pk_cubasdoc的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_cubasdoc() {
		 return pk_cubasdoc;
	  }   
	  
     /**
	   * 属性pk_cubasdoc的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_cubasdoc String
	   */
	public void setPk_cubasdoc(String newPk_cubasdoc) {
		
		pk_cubasdoc = newPk_cubasdoc;
	 } 	  
       
        /**
	   * 属性pk_defdoc3的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc3() {
		 return pk_defdoc3;
	  }   
	  
     /**
	   * 属性pk_defdoc3的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc3 String
	   */
	public void setPk_defdoc3(String newPk_defdoc3) {
		
		pk_defdoc3 = newPk_defdoc3;
	 } 	  
       
        /**
	   * 属性pk_defdoc12的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc12() {
		 return pk_defdoc12;
	  }   
	  
     /**
	   * 属性pk_defdoc12的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc12 String
	   */
	public void setPk_defdoc12(String newPk_defdoc12) {
		
		pk_defdoc12 = newPk_defdoc12;
	 } 	  
       
        /**
	   * 属性boutretflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFBoolean
	   */
	 public UFBoolean getBoutretflag() {
		 return boutretflag;
	  }   
	  
     /**
	   * 属性boutretflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newBoutretflag UFBoolean
	   */
	public void setBoutretflag(UFBoolean newBoutretflag) {
		
		boutretflag = newBoutretflag;
	 } 	  
       
        /**
	   * 属性vuserdef10的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef10() {
		 return vuserdef10;
	  }   
	  
     /**
	   * 属性vuserdef10的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef10 String
	   */
	public void setVuserdef10(String newVuserdef10) {
		
		vuserdef10 = newVuserdef10;
	 } 	  
       
        /**
	   * 属性cothercalbodyid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCothercalbodyid() {
		 return cothercalbodyid;
	  }   
	  
     /**
	   * 属性cothercalbodyid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCothercalbodyid String
	   */
	public void setCothercalbodyid(String newCothercalbodyid) {
		
		cothercalbodyid = newCothercalbodyid;
	 } 	  
       
        /**
	   * 属性pk_defdoc2的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc2() {
		 return pk_defdoc2;
	  }   
	  
     /**
	   * 属性pk_defdoc2的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc2 String
	   */
	public void setPk_defdoc2(String newPk_defdoc2) {
		
		pk_defdoc2 = newPk_defdoc2;
	 } 	  
       
        /**
	   * 属性vdiliveraddress的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVdiliveraddress() {
		 return vdiliveraddress;
	  }   
	  
     /**
	   * 属性vdiliveraddress的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVdiliveraddress String
	   */
	public void setVdiliveraddress(String newVdiliveraddress) {
		
		vdiliveraddress = newVdiliveraddress;
	 } 	  
       
        /**
	   * 属性pk_defdoc7的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc7() {
		 return pk_defdoc7;
	  }   
	  
     /**
	   * 属性pk_defdoc7的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc7 String
	   */
	public void setPk_defdoc7(String newPk_defdoc7) {
		
		pk_defdoc7 = newPk_defdoc7;
	 } 	  
       
        /**
	   * 属性pk_defdoc17的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc17() {
		 return pk_defdoc17;
	  }   
	  
     /**
	   * 属性pk_defdoc17的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc17 String
	   */
	public void setPk_defdoc17(String newPk_defdoc17) {
		
		pk_defdoc17 = newPk_defdoc17;
	 } 	  
       
        /**
	   * 属性ndiscountmny的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDouble
	   */
	 public UFDouble getNdiscountmny() {
		 return ndiscountmny;
	  }   
	  
     /**
	   * 属性ndiscountmny的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newNdiscountmny UFDouble
	   */
	public void setNdiscountmny(UFDouble newNdiscountmny) {
		
		ndiscountmny = newNdiscountmny;
	 } 	  
       
        /**
	   * 属性pk_cubasdocc的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_cubasdocc() {
		 return pk_cubasdocc;
	  }   
	  
     /**
	   * 属性pk_cubasdocc的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_cubasdocc String
	   */
	public void setPk_cubasdocc(String newPk_cubasdocc) {
		
		pk_cubasdocc = newPk_cubasdocc;
	 } 	  
       
        /**
	   * 属性pk_defdoc15的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc15() {
		 return pk_defdoc15;
	  }   
	  
     /**
	   * 属性pk_defdoc15的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc15 String
	   */
	public void setPk_defdoc15(String newPk_defdoc15) {
		
		pk_defdoc15 = newPk_defdoc15;
	 } 	  
       
        /**
	   * 属性vbillcode的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVbillcode() {
		 return vbillcode;
	  }   
	  
     /**
	   * 属性vbillcode的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVbillcode String
	   */
	public void setVbillcode(String newVbillcode) {
		
		vbillcode = newVbillcode;
	 } 	  
       
        /**
	   * 属性vuserdef12的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef12() {
		 return vuserdef12;
	  }   
	  
     /**
	   * 属性vuserdef12的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef12 String
	   */
	public void setVuserdef12(String newVuserdef12) {
		
		vuserdef12 = newVuserdef12;
	 } 	  
       
        /**
	   * 属性cinventoryid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCinventoryid() {
		 return cinventoryid;
	  }   
	  
     /**
	   * 属性cinventoryid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCinventoryid String
	   */
	public void setCinventoryid(String newCinventoryid) {
		
		cinventoryid = newCinventoryid;
	 } 	  
       
        /**
	   * 属性pk_defdoc16的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc16() {
		 return pk_defdoc16;
	  }   
	  
     /**
	   * 属性pk_defdoc16的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc16 String
	   */
	public void setPk_defdoc16(String newPk_defdoc16) {
		
		pk_defdoc16 = newPk_defdoc16;
	 } 	  
       
        /**
	   * 属性dauditdate的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDate
	   */
	 public UFDate getDauditdate() {
		 return dauditdate;
	  }   
	  
     /**
	   * 属性dauditdate的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newDauditdate UFDate
	   */
	public void setDauditdate(UFDate newDauditdate) {
		
		dauditdate = newDauditdate;
	 } 	  
       
        /**
	   * 属性pk_defdoc13的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc13() {
		 return pk_defdoc13;
	  }   
	  
     /**
	   * 属性pk_defdoc13的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc13 String
	   */
	public void setPk_defdoc13(String newPk_defdoc13) {
		
		pk_defdoc13 = newPk_defdoc13;
	 } 	  
       
        /**
	   * 属性vuserdef11的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef11() {
		 return vuserdef11;
	  }   
	  
     /**
	   * 属性vuserdef11的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef11 String
	   */
	public void setVuserdef11(String newVuserdef11) {
		
		vuserdef11 = newVuserdef11;
	 } 	  
       
        /**
	   * 属性vuserdef15的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef15() {
		 return vuserdef15;
	  }   
	  
     /**
	   * 属性vuserdef15的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef15 String
	   */
	public void setVuserdef15(String newVuserdef15) {
		
		vuserdef15 = newVuserdef15;
	 } 	  
       
        /**
	   * 属性pk_purcorp的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_purcorp() {
		 return pk_purcorp;
	  }   
	  
     /**
	   * 属性pk_purcorp的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_purcorp String
	   */
	public void setPk_purcorp(String newPk_purcorp) {
		
		pk_purcorp = newPk_purcorp;
	 } 	  
       
        /**
	   * 属性vuserdef17的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef17() {
		 return vuserdef17;
	  }   
	  
     /**
	   * 属性vuserdef17的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef17 String
	   */
	public void setVuserdef17(String newVuserdef17) {
		
		vuserdef17 = newVuserdef17;
	 } 	  
       
        /**
	   * 属性cothercorpid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCothercorpid() {
		 return cothercorpid;
	  }   
	  
     /**
	   * 属性cothercorpid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCothercorpid String
	   */
	public void setCothercorpid(String newCothercorpid) {
		
		cothercorpid = newCothercorpid;
	 } 	  
       
        /**
	   * 属性cdptid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCdptid() {
		 return cdptid;
	  }   
	  
     /**
	   * 属性cdptid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCdptid String
	   */
	public void setCdptid(String newCdptid) {
		
		cdptid = newCdptid;
	 } 	  
       
        /**
	   * 属性cdispatcherid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCdispatcherid() {
		 return cdispatcherid;
	  }   
	  
     /**
	   * 属性cdispatcherid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCdispatcherid String
	   */
	public void setCdispatcherid(String newCdispatcherid) {
		
		cdispatcherid = newCdispatcherid;
	 } 	  
       
        /**
	   * 属性cendreportid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCendreportid() {
		 return cendreportid;
	  }   
	  
     /**
	   * 属性cendreportid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCendreportid String
	   */
	public void setCendreportid(String newCendreportid) {
		
		cendreportid = newCendreportid;
	 } 	  
       
        /**
	   * 属性cbizid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCbizid() {
		 return cbizid;
	  }   
	  
     /**
	   * 属性cbizid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCbizid String
	   */
	public void setCbizid(String newCbizid) {
		
		cbizid = newCbizid;
	 } 	  
       
        /**
	   * 属性pk_defdoc18的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc18() {
		 return pk_defdoc18;
	  }   
	  
     /**
	   * 属性pk_defdoc18的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc18 String
	   */
	public void setPk_defdoc18(String newPk_defdoc18) {
		
		pk_defdoc18 = newPk_defdoc18;
	 } 	  
       
        /**
	   * 属性vheadnote2的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVheadnote2() {
		 return vheadnote2;
	  }   
	  
     /**
	   * 属性vheadnote2的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVheadnote2 String
	   */
	public void setVheadnote2(String newVheadnote2) {
		
		vheadnote2 = newVheadnote2;
	 } 	  
       
        /**
	   * 属性cbilltypecode的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCbilltypecode() {
		 return cbilltypecode;
	  }   
	  
     /**
	   * 属性cbilltypecode的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCbilltypecode String
	   */
	public void setCbilltypecode(String newCbilltypecode) {
		
		cbilltypecode = newCbilltypecode;
	 } 	  
       
        /**
	   * 属性pk_defdoc9的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc9() {
		 return pk_defdoc9;
	  }   
	  
     /**
	   * 属性pk_defdoc9的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc9 String
	   */
	public void setPk_defdoc9(String newPk_defdoc9) {
		
		pk_defdoc9 = newPk_defdoc9;
	 } 	  
       
        /**
	   * 属性tlastmoditime的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDateTime
	   */
	 public UFDateTime getTlastmoditime() {
		 return tlastmoditime;
	  }   
	  
     /**
	   * 属性tlastmoditime的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newTlastmoditime UFDateTime
	   */
	public void setTlastmoditime(UFDateTime newTlastmoditime) {
		
		tlastmoditime = newTlastmoditime;
	 } 	  
       
        /**
	   * 属性vuserdef1的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef1() {
		 return vuserdef1;
	  }   
	  
     /**
	   * 属性vuserdef1的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef1 String
	   */
	public void setVuserdef1(String newVuserdef1) {
		
		vuserdef1 = newVuserdef1;
	 } 	  
       
        /**
	   * 属性pk_calbody的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_calbody() {
		 return pk_calbody;
	  }   
	  
     /**
	   * 属性pk_calbody的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_calbody String
	   */
	public void setPk_calbody(String newPk_calbody) {
		
		pk_calbody = newPk_calbody;
	 } 	  
       
        /**
	   * 属性clastmodiid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getClastmodiid() {
		 return clastmodiid;
	  }   
	  
     /**
	   * 属性clastmodiid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newClastmodiid String
	   */
	public void setClastmodiid(String newClastmodiid) {
		
		clastmodiid = newClastmodiid;
	 } 	  
       
        /**
	   * 属性cproviderid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCproviderid() {
		 return cproviderid;
	  }   
	  
     /**
	   * 属性cproviderid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCproviderid String
	   */
	public void setCproviderid(String newCproviderid) {
		
		cproviderid = newCproviderid;
	 } 	  
       
        /**
	   * 属性pk_defdoc1的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc1() {
		 return pk_defdoc1;
	  }   
	  
     /**
	   * 属性pk_defdoc1的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc1 String
	   */
	public void setPk_defdoc1(String newPk_defdoc1) {
		
		pk_defdoc1 = newPk_defdoc1;
	 } 	  
       
        /**
	   * 属性cotherwhid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCotherwhid() {
		 return cotherwhid;
	  }   
	  
     /**
	   * 属性cotherwhid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCotherwhid String
	   */
	public void setCotherwhid(String newCotherwhid) {
		
		cotherwhid = newCotherwhid;
	 } 	  
       
        /**
	   * 属性dbilldate的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDate
	   */
	 public UFDate getDbilldate() {
		 return dbilldate;
	  }   
	  
     /**
	   * 属性dbilldate的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newDbilldate UFDate
	   */
	public void setDbilldate(UFDate newDbilldate) {
		
		dbilldate = newDbilldate;
	 } 	  
       
        /**
	   * 属性pk_defdoc19的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc19() {
		 return pk_defdoc19;
	  }   
	  
     /**
	   * 属性pk_defdoc19的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc19 String
	   */
	public void setPk_defdoc19(String newPk_defdoc19) {
		
		pk_defdoc19 = newPk_defdoc19;
	 } 	  
       
        /**
	   * 属性pk_defdoc4的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc4() {
		 return pk_defdoc4;
	  }   
	  
     /**
	   * 属性pk_defdoc4的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc4 String
	   */
	public void setPk_defdoc4(String newPk_defdoc4) {
		
		pk_defdoc4 = newPk_defdoc4;
	 } 	  
       
        /**
	   * 属性fspecialflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return Integer
	   */
	 public Integer getFspecialflag() {
		 return fspecialflag;
	  }   
	  
     /**
	   * 属性fspecialflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newFspecialflag Integer
	   */
	public void setFspecialflag(Integer newFspecialflag) {
		
		fspecialflag = newFspecialflag;
	 } 	  
       
        /**
	   * 属性pk_defdoc5的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc5() {
		 return pk_defdoc5;
	  }   
	  
     /**
	   * 属性pk_defdoc5的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc5 String
	   */
	public void setPk_defdoc5(String newPk_defdoc5) {
		
		pk_defdoc5 = newPk_defdoc5;
	 } 	  
       
        /**
	   * 属性vuserdef2的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef2() {
		 return vuserdef2;
	  }   
	  
     /**
	   * 属性vuserdef2的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef2 String
	   */
	public void setVuserdef2(String newVuserdef2) {
		
		vuserdef2 = newVuserdef2;
	 } 	  
       
        /**
	   * 属性cgeneralhid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCgeneralhid() {
		 return cgeneralhid;
	  }   
	  
     /**
	   * 属性cgeneralhid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCgeneralhid String
	   */
	public void setCgeneralhid(String newCgeneralhid) {
		
		cgeneralhid = newCgeneralhid;
	 } 	  
       
        /**
	   * 属性vuserdef5的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef5() {
		 return vuserdef5;
	  }   
	  
     /**
	   * 属性vuserdef5的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef5 String
	   */
	public void setVuserdef5(String newVuserdef5) {
		
		vuserdef5 = newVuserdef5;
	 } 	  
       
        /**
	   * 属性vuserdef16的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef16() {
		 return vuserdef16;
	  }   
	  
     /**
	   * 属性vuserdef16的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef16 String
	   */
	public void setVuserdef16(String newVuserdef16) {
		
		vuserdef16 = newVuserdef16;
	 } 	  
       
        /**
	   * 属性vnote的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVnote() {
		 return vnote;
	  }   
	  
     /**
	   * 属性vnote的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVnote String
	   */
	public void setVnote(String newVnote) {
		
		vnote = newVnote;
	 } 	  
       
        /**
	   * 属性vuserdef8的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef8() {
		 return vuserdef8;
	  }   
	  
     /**
	   * 属性vuserdef8的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef8 String
	   */
	public void setVuserdef8(String newVuserdef8) {
		
		vuserdef8 = newVuserdef8;
	 } 	  
       
        /**
	   * 属性coutcorpid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCoutcorpid() {
		 return coutcorpid;
	  }   
	  
     /**
	   * 属性coutcorpid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCoutcorpid String
	   */
	public void setCoutcorpid(String newCoutcorpid) {
		
		coutcorpid = newCoutcorpid;
	 } 	  
       
        /**
	   * 属性vuserdef4的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef4() {
		 return vuserdef4;
	  }   
	  
     /**
	   * 属性vuserdef4的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef4 String
	   */
	public void setVuserdef4(String newVuserdef4) {
		
		vuserdef4 = newVuserdef4;
	 } 	  
       
        /**
	   * 属性cregister的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCregister() {
		 return cregister;
	  }   
	  
     /**
	   * 属性cregister的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCregister String
	   */
	public void setCregister(String newCregister) {
		
		cregister = newCregister;
	 } 	  
       
        /**
	   * 属性pk_defdoc8的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc8() {
		 return pk_defdoc8;
	  }   
	  
     /**
	   * 属性pk_defdoc8的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc8 String
	   */
	public void setPk_defdoc8(String newPk_defdoc8) {
		
		pk_defdoc8 = newPk_defdoc8;
	 } 	  
       
        /**
	   * 属性daccountdate的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDate
	   */
	 public UFDate getDaccountdate() {
		 return daccountdate;
	  }   
	  
     /**
	   * 属性daccountdate的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newDaccountdate UFDate
	   */
	public void setDaccountdate(UFDate newDaccountdate) {
		
		daccountdate = newDaccountdate;
	 } 	  
       
        /**
	   * 属性vuserdef18的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef18() {
		 return vuserdef18;
	  }   
	  
     /**
	   * 属性vuserdef18的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef18 String
	   */
	public void setVuserdef18(String newVuserdef18) {
		
		vuserdef18 = newVuserdef18;
	 } 	  
       
        /**
	   * 属性vuserdef7的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef7() {
		 return vuserdef7;
	  }   
	  
     /**
	   * 属性vuserdef7的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef7 String
	   */
	public void setVuserdef7(String newVuserdef7) {
		
		vuserdef7 = newVuserdef7;
	 } 	  
       
        /**
	   * 属性fallocflag的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return Integer
	   */
	 public Integer getFallocflag() {
		 return fallocflag;
	  }   
	  
     /**
	   * 属性fallocflag的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newFallocflag Integer
	   */
	public void setFallocflag(Integer newFallocflag) {
		
		fallocflag = newFallocflag;
	 } 	  
       
        /**
	   * 属性pk_defdoc14的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getPk_defdoc14() {
		 return pk_defdoc14;
	  }   
	  
     /**
	   * 属性pk_defdoc14的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newPk_defdoc14 String
	   */
	public void setPk_defdoc14(String newPk_defdoc14) {
		
		pk_defdoc14 = newPk_defdoc14;
	 } 	  
       
        /**
	   * 属性nnetmny的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDouble
	   */
	 public UFDouble getNnetmny() {
		 return nnetmny;
	  }   
	  
     /**
	   * 属性nnetmny的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newNnetmny UFDouble
	   */
	public void setNnetmny(UFDouble newNnetmny) {
		
		nnetmny = newNnetmny;
	 } 	  
       
        /**
	   * 属性taccounttime的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return UFDateTime
	   */
	 public UFDateTime getTaccounttime() {
		 return taccounttime;
	  }   
	  
     /**
	   * 属性taccounttime的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newTaccounttime UFDateTime
	   */
	public void setTaccounttime(UFDateTime newTaccounttime) {
		
		taccounttime = newTaccounttime;
	 } 	  
       
        /**
	   * 属性vuserdef19的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef19() {
		 return vuserdef19;
	  }   
	  
     /**
	   * 属性vuserdef19的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef19 String
	   */
	public void setVuserdef19(String newVuserdef19) {
		
		vuserdef19 = newVuserdef19;
	 } 	  
       
        /**
	   * 属性cwarehouseid的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getCwarehouseid() {
		 return cwarehouseid;
	  }   
	  
     /**
	   * 属性cwarehouseid的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newCwarehouseid String
	   */
	public void setCwarehouseid(String newCwarehouseid) {
		
		cwarehouseid = newCwarehouseid;
	 } 	  
       
        /**
	   * 属性vuserdef13的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef13() {
		 return vuserdef13;
	  }   
	  
     /**
	   * 属性vuserdef13的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef13 String
	   */
	public void setVuserdef13(String newVuserdef13) {
		
		vuserdef13 = newVuserdef13;
	 } 	  
       
        /**
	   * 属性vuserdef6的Getter方法.
	   *
	   * 创建日期:2010-7-12
	   * @return String
	   */
	 public String getVuserdef6() {
		 return vuserdef6;
	  }   
	  
     /**
	   * 属性vuserdef6的Setter方法.
	   *
	   * 创建日期:2010-7-12
	   * @param newVuserdef6 String
	   */
	public void setVuserdef6(String newVuserdef6) {
		
		vuserdef6 = newVuserdef6;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2010-7-12
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_corp == null) {
			errFields.add(new String("pk_corp"));
			  }	
	   		if (cgeneralhid == null) {
			errFields.add(new String("cgeneralhid"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-7-12
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-7-12
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "cgeneralhid";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2010-7-12
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ic_general_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-7-12
	  */
	public IcGeneralHVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2010-7-12
	 * @param newCgeneralhid 主键值
	 */
	 public IcGeneralHVO(String newCgeneralhid) {
		
		// 为主键字段赋值:
		 cgeneralhid = newCgeneralhid;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-7-12
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return cgeneralhid;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-7-12
	  * @param newCgeneralhid  String    
	  */
	 public void setPrimaryKey(String newCgeneralhid) {
				
				cgeneralhid = newCgeneralhid; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2010-7-12
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ic_general_h"; 
				
	 } 
} 
