  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
    	package nc.vo.wds.ic.invstore;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * 
 *
 * <p>
 *     货位存货绑定主表
 * </p>
 *
 * 创建日期:2011-4-14
 * @author author
 * @version Your Project 1.0
 */
     public class CargdocVO extends SuperVO {
           
             public String reserve5;
             //仓库主键
             public String pk_stordoc;
             //仓库保管员
             public String pk_psndoc;
             public String reserve4;
             public UFDouble reserve10;
             //货位主键
             public String pk_cargdoc;
             public Integer dr;
             public UFDouble reserve8;
             public UFDouble reserve9;
             //主键
             public String pk_wds_cargdoc;
             public String reserve1;
             public UFDouble reserve7;
             public String vmemo;
             public UFDateTime ts;
             public String reserve2;
             public UFDouble reserve6;
             public String reserve3;
            
             public static final String  RESERVE5="reserve5";   
             public static final String  PK_STORDOC="pk_stordoc";   
             public static final String  RESERVE4="reserve4";   
             public static final String  RESERVE10="reserve10";   
             public static final String  PK_CARGDOC="pk_cargdoc";   
             public static final String  DR="dr";   
             public static final String  RESERVE8="reserve8";   
             public static final String  RESERVE9="reserve9";   
             public static final String  PK_WDS_CARGDOC="pk_wds_cargdoc";   
             public static final String  RESERVE1="reserve1";   
             public static final String  RESERVE7="reserve7";   
             public static final String  VMEMO="vmemo";   
             public static final String  TS="ts";   
             public static final String  RESERVE2="reserve2";   
             public static final String  RESERVE6="reserve6";   
             public static final String  RESERVE3="reserve3";   
      
    
        /**
	   * 属性reserve5的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getReserve5() {
		 return reserve5;
	  }   
	  
     /**
	   * 属性reserve5的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve5 String
	   */
	public void setReserve5(String newReserve5) {
		
		reserve5 = newReserve5;
	 } 	  
       
        /**
	   * 属性pk_stordoc的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getPk_stordoc() {
		 return pk_stordoc;
	  }   
	  
     public String getPk_psndoc() {
			return pk_psndoc;
		}

		public void setPk_psndoc(String pk_psndoc) {
			this.pk_psndoc = pk_psndoc;
		}

	/**
	   * 属性pk_stordoc的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newPk_stordoc String
	   */
	public void setPk_stordoc(String newPk_stordoc) {
		
		pk_stordoc = newPk_stordoc;
	 } 	  
       
        /**
	   * 属性reserve4的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getReserve4() {
		 return reserve4;
	  }   
	  
     /**
	   * 属性reserve4的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve4 String
	   */
	public void setReserve4(String newReserve4) {
		
		reserve4 = newReserve4;
	 } 	  
       
        /**
	   * 属性reserve10的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDouble
	   */
	 public UFDouble getReserve10() {
		 return reserve10;
	  }   
	  
     /**
	   * 属性reserve10的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve10 UFDouble
	   */
	public void setReserve10(UFDouble newReserve10) {
		
		reserve10 = newReserve10;
	 } 	  
       
        /**
	   * 属性pk_cargdoc的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getPk_cargdoc() {
		 return pk_cargdoc;
	  }   
	  
     /**
	   * 属性pk_cargdoc的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newPk_cargdoc String
	   */
	public void setPk_cargdoc(String newPk_cargdoc) {
		
		pk_cargdoc = newPk_cargdoc;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性reserve8的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDouble
	   */
	 public UFDouble getReserve8() {
		 return reserve8;
	  }   
	  
     /**
	   * 属性reserve8的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve8 UFDouble
	   */
	public void setReserve8(UFDouble newReserve8) {
		
		reserve8 = newReserve8;
	 } 	  
       
        /**
	   * 属性reserve9的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDouble
	   */
	 public UFDouble getReserve9() {
		 return reserve9;
	  }   
	  
     /**
	   * 属性reserve9的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve9 UFDouble
	   */
	public void setReserve9(UFDouble newReserve9) {
		
		reserve9 = newReserve9;
	 } 	  
       
        /**
	   * 属性pk_wds_cargdoc的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getPk_wds_cargdoc() {
		 return pk_wds_cargdoc;
	  }   
	  
     /**
	   * 属性pk_wds_cargdoc的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newPk_wds_cargdoc String
	   */
	public void setPk_wds_cargdoc(String newPk_wds_cargdoc) {
		
		pk_wds_cargdoc = newPk_wds_cargdoc;
	 } 	  
       
        /**
	   * 属性reserve1的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getReserve1() {
		 return reserve1;
	  }   
	  
     /**
	   * 属性reserve1的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve1 String
	   */
	public void setReserve1(String newReserve1) {
		
		reserve1 = newReserve1;
	 } 	  
       
        /**
	   * 属性reserve7的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDouble
	   */
	 public UFDouble getReserve7() {
		 return reserve7;
	  }   
	  
     /**
	   * 属性reserve7的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve7 UFDouble
	   */
	public void setReserve7(UFDouble newReserve7) {
		
		reserve7 = newReserve7;
	 } 	  
       
        /**
	   * 属性vmemo的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getVmemo() {
		 return vmemo;
	  }   
	  
     /**
	   * 属性vmemo的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newVmemo String
	   */
	public void setVmemo(String newVmemo) {
		
		vmemo = newVmemo;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性reserve2的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getReserve2() {
		 return reserve2;
	  }   
	  
     /**
	   * 属性reserve2的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve2 String
	   */
	public void setReserve2(String newReserve2) {
		
		reserve2 = newReserve2;
	 } 	  
       
        /**
	   * 属性reserve6的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return UFDouble
	   */
	 public UFDouble getReserve6() {
		 return reserve6;
	  }   
	  
     /**
	   * 属性reserve6的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve6 UFDouble
	   */
	public void setReserve6(UFDouble newReserve6) {
		
		reserve6 = newReserve6;
	 } 	  
       
        /**
	   * 属性reserve3的Getter方法.
	   *
	   * 创建日期:2011-4-14
	   * @return String
	   */
	 public String getReserve3() {
		 return reserve3;
	  }   
	  
     /**
	   * 属性reserve3的Setter方法.
	   *
	   * 创建日期:2011-4-14
	   * @param newReserve3 String
	   */
	public void setReserve3(String newReserve3) {
		
		reserve3 = newReserve3;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-4-14
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_wds_cargdoc == null) {
			errFields.add(new String("pk_wds_cargdoc"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-4-14
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-4-14
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_wds_cargdoc";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-4-14
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "wds_cargdoc1";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-4-14
	  */
	public CargdocVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-4-14
	 * @param newPk_wds_cargdoc 主键值
	 */
	 public CargdocVO(String newPk_wds_cargdoc) {
		
		// 为主键字段赋值:
		 pk_wds_cargdoc = newPk_wds_cargdoc;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-14
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_wds_cargdoc;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-4-14
	  * @param newPk_wds_cargdoc  String    
	  */
	 public void setPrimaryKey(String newPk_wds_cargdoc) {
				
				pk_wds_cargdoc = newPk_wds_cargdoc; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-4-14
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "wds_cargdoc1"; 
				
	 } 
} 
