  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.wds.w80021016;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2010-12-23
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class TbHandlingacqVO extends SuperVO {
           
             public String pk_customize1;
             public String pk_customize3;
             public String haq_customize3;
             public String haq_customize1;
             public String ts;
             public Integer dr;
             public UFDouble haq_dj;
             public String vnote;
             public String pk_customize2;
             public String haq_customize2;
             public String pk_haq;
            
             public static final String  PK_CUSTOMIZE1="pk_customize1";   
             public static final String  PK_CUSTOMIZE3="pk_customize3";   
             public static final String  HAQ_CUSTOMIZE3="haq_customize3";   
             public static final String  HAQ_CUSTOMIZE1="haq_customize1";   
             public static final String  TS="ts";   
             public static final String  DR="dr";   
             public static final String  HAQ_DJ="haq_dj";   
             public static final String  VNOTE="vnote";   
             public static final String  PK_CUSTOMIZE2="pk_customize2";   
             public static final String  HAQ_CUSTOMIZE2="haq_customize2";   
             public static final String  PK_HAQ="pk_haq";   
      
    
        /**
	   * 属性pk_customize1的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getPk_customize1() {
		 return pk_customize1;
	  }   
	  
     /**
	   * 属性pk_customize1的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newPk_customize1 String
	   */
	public void setPk_customize1(String newPk_customize1) {
		
		pk_customize1 = newPk_customize1;
	 } 	  
       
        /**
	   * 属性pk_customize3的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getPk_customize3() {
		 return pk_customize3;
	  }   
	  
     /**
	   * 属性pk_customize3的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newPk_customize3 String
	   */
	public void setPk_customize3(String newPk_customize3) {
		
		pk_customize3 = newPk_customize3;
	 } 	  
       
        /**
	   * 属性haq_customize3的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getHaq_customize3() {
		 return haq_customize3;
	  }   
	  
     /**
	   * 属性haq_customize3的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newHaq_customize3 String
	   */
	public void setHaq_customize3(String newHaq_customize3) {
		
		haq_customize3 = newHaq_customize3;
	 } 	  
       
        /**
	   * 属性haq_customize1的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getHaq_customize1() {
		 return haq_customize1;
	  }   
	  
     /**
	   * 属性haq_customize1的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newHaq_customize1 String
	   */
	public void setHaq_customize1(String newHaq_customize1) {
		
		haq_customize1 = newHaq_customize1;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newTs String
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性haq_dj的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return UFDouble
	   */
	 public UFDouble getHaq_dj() {
		 return haq_dj;
	  }   
	  
     /**
	   * 属性haq_dj的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newHaq_dj UFDouble
	   */
	public void setHaq_dj(UFDouble newHaq_dj) {
		
		haq_dj = newHaq_dj;
	 } 	  
       
        /**
	   * 属性vnote的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getVnote() {
		 return vnote;
	  }   
	  
     /**
	   * 属性vnote的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newVnote String
	   */
	public void setVnote(String newVnote) {
		
		vnote = newVnote;
	 } 	  
       
        /**
	   * 属性pk_customize2的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getPk_customize2() {
		 return pk_customize2;
	  }   
	  
     /**
	   * 属性pk_customize2的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newPk_customize2 String
	   */
	public void setPk_customize2(String newPk_customize2) {
		
		pk_customize2 = newPk_customize2;
	 } 	  
       
        /**
	   * 属性haq_customize2的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getHaq_customize2() {
		 return haq_customize2;
	  }   
	  
     /**
	   * 属性haq_customize2的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newHaq_customize2 String
	   */
	public void setHaq_customize2(String newHaq_customize2) {
		
		haq_customize2 = newHaq_customize2;
	 } 	  
       
        /**
	   * 属性pk_haq的Getter方法.
	   *
	   * 创建日期:2010-12-23
	   * @return String
	   */
	 public String getPk_haq() {
		 return pk_haq;
	  }   
	  
     /**
	   * 属性pk_haq的Setter方法.
	   *
	   * 创建日期:2010-12-23
	   * @param newPk_haq String
	   */
	public void setPk_haq(String newPk_haq) {
		
		pk_haq = newPk_haq;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2010-12-23
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-12-23
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-12-23
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_haq";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2010-12-23
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "tb_handlingacq";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-12-23
	  */
	public TbHandlingacqVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2010-12-23
	 * @param newPk_haq 主键值
	 */
	 public TbHandlingacqVO(String newPk_haq) {
		
		// 为主键字段赋值:
		 pk_haq = newPk_haq;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-12-23
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_haq;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-12-23
	  * @param newPk_haq  String    
	  */
	 public void setPrimaryKey(String newPk_haq) {
				
				pk_haq = newPk_haq; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2010-12-23
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "tb_handlingacq"; 
				
	 } 
} 
