  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.wds.w80060804;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2010-6-26
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class TbTranscompanyKVO extends SuperVO {
           
             public String tck_customize2;
             public String tck_manager;
             public String tck_account;
             public String tck_pk;
             public String tck_customize3;
             public Integer dr;
             public String vnote;
             public String tc_pk;
             public String tck_bankname;
             public String tck_bankphone;
             public String tck_customize4;
             public String tck_bankaddress;
             public UFTime ts;
             public String tck_bankemail;
             public String tck_customize1;
             public String tck_customize5;
            
             public static final String  TCK_CUSTOMIZE2="tck_customize2";   
             public static final String  TCK_MANAGER="tck_manager";   
             public static final String  TCK_ACCOUNT="tck_account";   
             public static final String  TCK_PK="tck_pk";   
             public static final String  TCK_CUSTOMIZE3="tck_customize3";   
             public static final String  DR="dr";   
             public static final String  VNOTE="vnote";   
             public static final String  TC_PK="tc_pk";   
             public static final String  TCK_BANKNAME="tck_bankname";   
             public static final String  TCK_BANKPHONE="tck_bankphone";   
             public static final String  TCK_CUSTOMIZE4="tck_customize4";   
             public static final String  TCK_BANKADDRESS="tck_bankaddress";   
             public static final String  TS="ts";   
             public static final String  TCK_BANKEMAIL="tck_bankemail";   
             public static final String  TCK_CUSTOMIZE1="tck_customize1";   
             public static final String  TCK_CUSTOMIZE5="tck_customize5";   
      
    
        /**
	   * 属性tck_customize2的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_customize2() {
		 return tck_customize2;
	  }   
	  
     /**
	   * 属性tck_customize2的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_customize2 String
	   */
	public void setTck_customize2(String newTck_customize2) {
		
		tck_customize2 = newTck_customize2;
	 } 	  
       
        /**
	   * 属性tck_manager的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_manager() {
		 return tck_manager;
	  }   
	  
     /**
	   * 属性tck_manager的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_manager String
	   */
	public void setTck_manager(String newTck_manager) {
		
		tck_manager = newTck_manager;
	 } 	  
       
        /**
	   * 属性tck_account的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_account() {
		 return tck_account;
	  }   
	  
     /**
	   * 属性tck_account的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_account String
	   */
	public void setTck_account(String newTck_account) {
		
		tck_account = newTck_account;
	 } 	  
       
        /**
	   * 属性tck_pk的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_pk() {
		 return tck_pk;
	  }   
	  
     /**
	   * 属性tck_pk的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_pk String
	   */
	public void setTck_pk(String newTck_pk) {
		
		tck_pk = newTck_pk;
	 } 	  
       
        /**
	   * 属性tck_customize3的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_customize3() {
		 return tck_customize3;
	  }   
	  
     /**
	   * 属性tck_customize3的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_customize3 String
	   */
	public void setTck_customize3(String newTck_customize3) {
		
		tck_customize3 = newTck_customize3;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性vnote的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getVnote() {
		 return vnote;
	  }   
	  
     /**
	   * 属性vnote的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newVnote String
	   */
	public void setVnote(String newVnote) {
		
		vnote = newVnote;
	 } 	  
       
        /**
	   * 属性tc_pk的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTc_pk() {
		 return tc_pk;
	  }   
	  
     /**
	   * 属性tc_pk的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTc_pk String
	   */
	public void setTc_pk(String newTc_pk) {
		
		tc_pk = newTc_pk;
	 } 	  
       
        /**
	   * 属性tck_bankname的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_bankname() {
		 return tck_bankname;
	  }   
	  
     /**
	   * 属性tck_bankname的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_bankname String
	   */
	public void setTck_bankname(String newTck_bankname) {
		
		tck_bankname = newTck_bankname;
	 } 	  
       
        /**
	   * 属性tck_bankphone的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_bankphone() {
		 return tck_bankphone;
	  }   
	  
     /**
	   * 属性tck_bankphone的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_bankphone String
	   */
	public void setTck_bankphone(String newTck_bankphone) {
		
		tck_bankphone = newTck_bankphone;
	 } 	  
       
        /**
	   * 属性tck_customize4的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_customize4() {
		 return tck_customize4;
	  }   
	  
     /**
	   * 属性tck_customize4的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_customize4 String
	   */
	public void setTck_customize4(String newTck_customize4) {
		
		tck_customize4 = newTck_customize4;
	 } 	  
       
        /**
	   * 属性tck_bankaddress的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_bankaddress() {
		 return tck_bankaddress;
	  }   
	  
     /**
	   * 属性tck_bankaddress的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_bankaddress String
	   */
	public void setTck_bankaddress(String newTck_bankaddress) {
		
		tck_bankaddress = newTck_bankaddress;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return UFDateTime
	   */
	 public UFTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTs UFDateTime
	   */
	public void setTs(UFTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性tck_bankemail的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_bankemail() {
		 return tck_bankemail;
	  }   
	  
     /**
	   * 属性tck_bankemail的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_bankemail String
	   */
	public void setTck_bankemail(String newTck_bankemail) {
		
		tck_bankemail = newTck_bankemail;
	 } 	  
       
        /**
	   * 属性tck_customize1的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_customize1() {
		 return tck_customize1;
	  }   
	  
     /**
	   * 属性tck_customize1的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_customize1 String
	   */
	public void setTck_customize1(String newTck_customize1) {
		
		tck_customize1 = newTck_customize1;
	 } 	  
       
        /**
	   * 属性tck_customize5的Getter方法.
	   *
	   * 创建日期:2010-6-26
	   * @return String
	   */
	 public String getTck_customize5() {
		 return tck_customize5;
	  }   
	  
     /**
	   * 属性tck_customize5的Setter方法.
	   *
	   * 创建日期:2010-6-26
	   * @param newTck_customize5 String
	   */
	public void setTck_customize5(String newTck_customize5) {
		
		tck_customize5 = newTck_customize5;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2010-6-26
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (tck_pk == null) {
			errFields.add(new String("tck_pk"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-6-26
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "tc_pk";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-6-26
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "tck_pk";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2010-6-26
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "tb_transcompany_k";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-6-26
	  */
	public TbTranscompanyKVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2010-6-26
	 * @param newTck_pk 主键值
	 */
	 public TbTranscompanyKVO(String newTck_pk) {
		
		// 为主键字段赋值:
		 tck_pk = newTck_pk;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-6-26
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return tck_pk;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-6-26
	  * @param newTck_pk  String    
	  */
	 public void setPrimaryKey(String newTck_pk) {
				
				tck_pk = newTck_pk; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2010-6-26
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "tb_transcompany_k"; 
				
	 } 
} 
