/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wds.load.account;

import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;

/**
 * <b> 装卸费结算主表 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-5-3
 * @author author
 * @version Your Project 1.0
 */
public class LoadpriceHVO extends SuperVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1182241012463851480L;
	
	public String pk_loadprice;//主键
	public Integer floadtype;//费用类型
	public UFDouble vzfee;// 合计总费用
	public String pk_stordoc;//仓库
	//预留字段
	public String reserve1;
	public String reserve2;
	public String reserve3;
	public String reserve4;	
	public String reserve5;
	public UFDouble reserve6;
	public UFDouble reserve7;
	public UFDouble reserve8;
	public UFDouble reserve9;	
	public UFDouble reserve10;
	public UFDate reserve11;
	public UFDate reserve12;
	public UFDate reserve13;	
	public UFBoolean reserve14;//是否冻结
	public UFBoolean reserve15;
	public UFBoolean reserve16;	
	//自定义项
	public String vdef1;
	public String vdef2;
	public String vdef3;
	public String vdef4;	
	public String vdef5;
	public String vdef6;
	public String vdef7;
	public String vdef8;
	public String vdef9;
	public String vdef10;
	public UFDateTime ts;
	public Integer dr;
	//备注
	public String vmemo;
	//公司
	 public String pk_corp;     
	 //单据号
	 public String vbillno;
	 //单据日期
	 public UFDate dbilldate;
	 //单据类型
	 public String pk_billtype;
	 //单据状态
	 public Integer vbillstatus;
	 //业务类型
	 public String pk_busitype;
	//业务员id
	 public String vemployeeid;
	 //部门id
	 public String pk_deptdoc;  
	 //制单人
	 public String voperatorid;
	 //制单日期
	 public UFDate dmakedate;         
	 //审批人
	 public String vapproveid;
	 //审批日期
	 public UFDate dapprovedate;
	 //审批批语
	 public String vapprovenote;

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性vdef4的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newVdef4
	 *            String
	 * 
	 * 属性dmakedate的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * @return UFDate
	 */
	public UFDate getDmakedate() {
		return dmakedate;
	}

	/**
	 * 属性dmakedate的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newDmakedate
	 *            UFDate
	 */
	public void setDmakedate(UFDate newDmakedate) {

		dmakedate = newDmakedate;
	}

	/**
	 * 属性pk_loadprice的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getPk_loadprice() {
		return pk_loadprice;
	}

	/**
	 * 属性pk_loadprice的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newPk_loadprice
	 *            String
	 */
	public void setPk_loadprice(String newPk_loadprice) {

		pk_loadprice = newPk_loadprice;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性voperatorid的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getVoperatorid() {
		return voperatorid;
	}

	/**
	 * 属性voperatorid的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newVoperatorid
	 *            String
	 */
	public void setVoperatorid(String newVoperatorid) {

		voperatorid = newVoperatorid;
	}

	/**
	 * 属性vapprovenote的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getVapprovenote() {
		return vapprovenote;
	}

	/**
	 * 属性vapprovenote的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newVapprovenote
	 *            String
	 */
	public void setVapprovenote(String newVapprovenote) {

		vapprovenote = newVapprovenote;
	}

	/**
	 * 属性pk_billtype的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getPk_billtype() {
		return pk_billtype;
	}

	/**
	 * 属性pk_billtype的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newPk_billtype
	 *            String
	 */
	public void setPk_billtype(String newPk_billtype) {

		pk_billtype = newPk_billtype;
	}

	/**
	 * 属性vbillstatus的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return Integer
	 */
	public Integer getVbillstatus() {
		return vbillstatus;
	}

	/**
	 * 属性vbillstatus的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newVbillstatus
	 *            Integer
	 */
	public void setVbillstatus(Integer newVbillstatus) {

		vbillstatus = newVbillstatus;
	}

	/**
	 * 属性vemployeeid的Getter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @return String
	 */
	public String getVemployeeid() {
		return vemployeeid;
	}

	/**
	 * 属性vemployeeid的Setter方法.
	 * 
	 * 创建日期:2011-5-3
	 * 
	 * @param newVemployeeid
	 *            String
	 */
	public void setVemployeeid(String newVemployeeid) {

		vemployeeid = newVemployeeid;
	}

	public String getVmemo() {
		return vmemo;
	}

	public void setVmemo(String vmemo) {
		this.vmemo = vmemo;
	}

	public UFDateTime getTs() {
		return ts;
	}

	public void setTs(UFDateTime ts) {
		this.ts = ts;
	}

	public String getPk_busitype() {
		return pk_busitype;
	}

	public void setPk_busitype(String pk_busitype) {
		this.pk_busitype = pk_busitype;
	}

	public UFDate getDbilldate() {
		return dbilldate;
	}

	public void setDbilldate(UFDate dbilldate) {
		this.dbilldate = dbilldate;
	}

	public String getVbillno() {
		return vbillno;
	}

	public void setVbillno(String vbillno) {
		this.vbillno = vbillno;
	}

	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	public void setPk_deptdoc(String pk_deptdoc) {
		this.pk_deptdoc = pk_deptdoc;
	}

	public Integer getFloadtype() {
		return floadtype;
	}

	public void setFloadtype(Integer floadtype) {
		this.floadtype = floadtype;
	}

	public UFDate getDapprovedate() {
		return dapprovedate;
	}

	public void setDapprovedate(UFDate dapprovedate) {
		this.dapprovedate = dapprovedate;
	}

	public String getVapproveid() {
		return vapproveid;
	}

	public void setVapproveid(String vapproveid) {
		this.vapproveid = vapproveid;
	}

	public UFDouble getVzfee() {
		return vzfee;
	}

	public void setVzfee(UFDouble vzfee) {
		this.vzfee = vzfee;
	}

	@Override
	public String getPKFieldName() {

		return "pk_loadprice";
	}

	@Override
	public String getParentPKFieldName() {

		return null;
	}

	@Override
	public String getTableName() {

		return "wds_loadprice_h";
	}

	public String getPk_stordoc() {
		return pk_stordoc;
	}

	public void setPk_stordoc(String pk_stordoc) {
		this.pk_stordoc = pk_stordoc;
	}

	public String getReserve1() {
		return reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public String getReserve4() {
		return reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	public String getReserve5() {
		return reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

	public UFDouble getReserve6() {
		return reserve6;
	}

	public void setReserve6(UFDouble reserve6) {
		this.reserve6 = reserve6;
	}

	public UFDouble getReserve7() {
		return reserve7;
	}

	public void setReserve7(UFDouble reserve7) {
		this.reserve7 = reserve7;
	}

	public UFDouble getReserve8() {
		return reserve8;
	}

	public void setReserve8(UFDouble reserve8) {
		this.reserve8 = reserve8;
	}

	public UFDouble getReserve9() {
		return reserve9;
	}

	public void setReserve9(UFDouble reserve9) {
		this.reserve9 = reserve9;
	}

	public UFDouble getReserve10() {
		return reserve10;
	}

	public void setReserve10(UFDouble reserve10) {
		this.reserve10 = reserve10;
	}

	public UFDate getReserve11() {
		return reserve11;
	}

	public void setReserve11(UFDate reserve11) {
		this.reserve11 = reserve11;
	}

	public UFDate getReserve12() {
		return reserve12;
	}

	public void setReserve12(UFDate reserve12) {
		this.reserve12 = reserve12;
	}

	public UFDate getReserve13() {
		return reserve13;
	}

	public void setReserve13(UFDate reserve13) {
		this.reserve13 = reserve13;
	}

	public UFBoolean getReserve14() {
		return reserve14;
	}

	public void setReserve14(UFBoolean reserve14) {
		this.reserve14 = reserve14;
	}

	public UFBoolean getReserve15() {
		return reserve15;
	}

	public void setReserve15(UFBoolean reserve15) {
		this.reserve15 = reserve15;
	}

	public UFBoolean getReserve16() {
		return reserve16;
	}

	public void setReserve16(UFBoolean reserve16) {
		this.reserve16 = reserve16;
	}

	public String getVdef1() {
		return vdef1;
	}

	public void setVdef1(String vdef1) {
		this.vdef1 = vdef1;
	}

	public String getVdef2() {
		return vdef2;
	}

	public void setVdef2(String vdef2) {
		this.vdef2 = vdef2;
	}

	public String getVdef3() {
		return vdef3;
	}

	public void setVdef3(String vdef3) {
		this.vdef3 = vdef3;
	}

	public String getVdef4() {
		return vdef4;
	}

	public void setVdef4(String vdef4) {
		this.vdef4 = vdef4;
	}

	public String getVdef5() {
		return vdef5;
	}

	public void setVdef5(String vdef5) {
		this.vdef5 = vdef5;
	}

	public String getVdef6() {
		return vdef6;
	}

	public void setVdef6(String vdef6) {
		this.vdef6 = vdef6;
	}

	public String getVdef7() {
		return vdef7;
	}

	public void setVdef7(String vdef7) {
		this.vdef7 = vdef7;
	}

	public String getVdef8() {
		return vdef8;
	}

	public void setVdef8(String vdef8) {
		this.vdef8 = vdef8;
	}

	public String getVdef9() {
		return vdef9;
	}

	public void setVdef9(String vdef9) {
		this.vdef9 = vdef9;
	}

	public String getVdef10() {
		return vdef10;
	}

	public void setVdef10(String vdef10) {
		this.vdef10 = vdef10;
	}

}
