  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.wds.load.account;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 装卸费结算来源明细子表</b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2011-5-3
 * @author author
 * @version Your Project 1.0
 */
     public class LoadpriceB1VO extends SuperVO {
           
             public String reserve5;
             public String vdef4;     
             public String pk_loadprice;
             public Integer dr;
             public UFDate reserve12;
             public UFDateTime ts;
             public UFDouble reserve6;
             public UFBoolean reserve14;
             public UFDouble reserve10;
             public String vdef3;
             public String pk_invmandoc;//存货管理id
             public String pk_invbasdoc;//存货基本id
             public String vbatchecode;//批次号
             public UFDouble nhsl;//换算率
             public String reserve1;
             public UFBoolean reserve16;
           
             public UFBoolean reserve15;
             public String reserve2;
             
             public String vdef10;
             public String vdef5;
             public String reserve4;           
             public String vdef7;
            
             public String vdef2;
             public UFDate reserve11;
             public String vmemo;            
             public String vdef1;
             public String reserve3;        
             public UFDate reserve13;
             public UFDouble reserve9;
             public UFDouble reserve8;
             public String vdef9;  
             public String vdef8;            
             public UFDouble reserve7;
             public String vdef6;
             public String pk_loadprice_b1;      
             public String csourcebillhid;
             public String csourcetype;
             public String csourcebillbid;
             public String vsourcebillcode;          
             public String cfirstbillhid;
             public String cfirstbillbid;
             public String vfirstbillcode;
             public String cfirsttype;   
             public UFDouble nloadprice;//装货费用
             public UFDouble nunloadprice;//卸货费用
             public UFDouble ncodeprice;//采码费用
             public UFDouble ntagprice;//贴签费用
             public UFDouble noutnum;//实出数量
             public UFDouble nassoutnum;//实出辅数量
             public UFDouble nshouldoutnum;//应出数量
             public UFDouble nassshouldoutnum;//应出辅数量
             public UFDouble ntagnum;//贴签数量
             public String cunitid;//主计量单位
             public String cassunitid;//辅计量单位
             
             public static final  String CUNITID="cunitid";
             public static final  String CASSUNITID="cassunitid";
             public static final String  RESERVE5="reserve5";   
             public static final String  CSOURCEBILLHID="csourcebillhid";   
             public static final String  VDEF4="vdef4";   
             public static final String  VFIRSTBILLCODE="vfirstbillcode";   
             public static final String  PK_LOADPRICE="pk_loadprice";   
             public static final String  CSOURCETYPE="csourcetype";   
             public static final String  DR="dr";   
             public static final String  RESERVE12="reserve12";   
             public static final String  TS="ts";   
             public static final String  NOUTNUM="noutnum";   
             public static final String  RESERVE6="reserve6";   
             public static final String  RESERVE14="reserve14";   
             public static final String  RESERVE10="reserve10";   
             public static final String  VDEF3="vdef3";   
             public static final String  VBATCHECODE="vbatchecode";   
             public static final String  NHSL="nhsl";   
             public static final String  RESERVE1="reserve1";   
             public static final String  RESERVE16="reserve16";   
             public static final String  NSHOULDOUTNUM="nshouldoutnum";   
             public static final String  NLOADPRICE="nloasprice";   
             public static final String  RESERVE15="reserve15";   
             public static final String  RESERVE2="reserve2";   
             public static final String  PK_INVMANDOC="pk_invmandoc";   
             public static final String  VDEF10="vdef10";   
             public static final String  VDEF5="vdef5";   
             public static final String  CFIRSTBILLBID="cfirstbillbid";   
             public static final String  RESERVE4="reserve4";   
             public static final String  CFIRSTBILLHID="cfirstbillhid";   
             public static final String  NCODEPRICE="ncodeprice";   
             public static final String  VDEF7="vdef7";   
             public static final String  NUNLOADPRICE="nunloadprice";   
             public static final String  NTAGPRICE="ntagprice";   
             public static final String  PK_INVBASDOC="pk_invbasdoc";   
             public static final String  VDEF2="vdef2";   
             public static final String  RESERVE11="reserve11";   
             public static final String  VMEMO="vmemo";   
             public static final String  NASSOUTNUM="nassoutnum";   
             public static final String  VSOURCEBILLCODE="vsourcebillcode";   
             public static final String  VDEF1="vdef1";   
             public static final String  RESERVE3="reserve3";   
             public static final String  CSOURCEBILLBID="csourcebillbid";   
             public static final String  RESERVE13="reserve13";   
             public static final String  NASSSHOULDOUTNUM="nassshouldoutnum";   
             public static final String  RESERVE9="reserve9";   
             public static final String  RESERVE8="reserve8";   
             public static final String  VDEF9="vdef9";   
             public static final String  PK_LOADPRICE_B1="pk_loadprice_b1";   
             public static final String  VDEF8="vdef8";   
             public static final String  CFIRSTTYPE="cfirsttype";   
             public static final String  RESERVE7="reserve7";   
             public static final String  VDEF6="vdef6";   
      
    
        /**
	   * 属性reserve5的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getReserve5() {
		 return reserve5;
	  }   
	  
     /**
	   * 属性reserve5的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve5 String
	   */
	public void setReserve5(String newReserve5) {
		
		reserve5 = newReserve5;
	 } 	  
       
        /**
	   * 属性csourcebillhid的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCsourcebillhid() {
		 return csourcebillhid;
	  }   
	  
     /**
	   * 属性csourcebillhid的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCsourcebillhid String
	   */
	public void setCsourcebillhid(String newCsourcebillhid) {
		
		csourcebillhid = newCsourcebillhid;
	 } 	  
       
        /**
	   * 属性vdef4的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef4() {
		 return vdef4;
	  }   
	  
     /**
	   * 属性vdef4的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef4 String
	   */
	public void setVdef4(String newVdef4) {
		
		vdef4 = newVdef4;
	 } 	  
       
        /**
	   * 属性vfirstbillcode的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVfirstbillcode() {
		 return vfirstbillcode;
	  }   
	  
     /**
	   * 属性vfirstbillcode的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVfirstbillcode String
	   */
	public void setVfirstbillcode(String newVfirstbillcode) {
		
		vfirstbillcode = newVfirstbillcode;
	 } 	  
       
        /**
	   * 属性pk_loadprice的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getPk_loadprice() {
		 return pk_loadprice;
	  }   
	  
     /**
	   * 属性pk_loadprice的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newPk_loadprice String
	   */
	public void setPk_loadprice(String newPk_loadprice) {
		
		pk_loadprice = newPk_loadprice;
	 } 	  
       
        /**
	   * 属性csourcetype的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCsourcetype() {
		 return csourcetype;
	  }   
	  
     /**
	   * 属性csourcetype的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCsourcetype String
	   */
	public void setCsourcetype(String newCsourcetype) {
		
		csourcetype = newCsourcetype;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性reserve12的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDate
	   */
	 public UFDate getReserve12() {
		 return reserve12;
	  }   
	  
     /**
	   * 属性reserve12的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve12 UFDate
	   */
	public void setReserve12(UFDate newReserve12) {
		
		reserve12 = newReserve12;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性noutnum的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNoutnum() {
		 return noutnum;
	  }   
	  
     /**
	   * 属性noutnum的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNoutnum UFDouble
	   */
	public void setNoutnum(UFDouble newNoutnum) {
		
		noutnum = newNoutnum;
	 } 	  
       
        /**
	   * 属性reserve6的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getReserve6() {
		 return reserve6;
	  }   
	  
     /**
	   * 属性reserve6的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve6 UFDouble
	   */
	public void setReserve6(UFDouble newReserve6) {
		
		reserve6 = newReserve6;
	 } 	  
       
        /**
	   * 属性reserve14的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFBoolean
	   */
	 public UFBoolean getReserve14() {
		 return reserve14;
	  }   
	  
     /**
	   * 属性reserve14的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve14 UFBoolean
	   */
	public void setReserve14(UFBoolean newReserve14) {
		
		reserve14 = newReserve14;
	 } 	  
       
        /**
	   * 属性reserve10的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getReserve10() {
		 return reserve10;
	  }   
	  
     /**
	   * 属性reserve10的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve10 UFDouble
	   */
	public void setReserve10(UFDouble newReserve10) {
		
		reserve10 = newReserve10;
	 } 	  
       
        /**
	   * 属性vdef3的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef3() {
		 return vdef3;
	  }   
	  
     /**
	   * 属性vdef3的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef3 String
	   */
	public void setVdef3(String newVdef3) {
		
		vdef3 = newVdef3;
	 } 	  
       
        /**
	   * 属性vbatchecode的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVbatchecode() {
		 return vbatchecode;
	  }   
	  
     /**
	   * 属性vbatchecode的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVbatchecode String
	   */
	public void setVbatchecode(String newVbatchecode) {
		
		vbatchecode = newVbatchecode;
	 } 	  
       
        /**
	   * 属性nhsl的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNhsl() {
		 return nhsl;
	  }   
	  
     /**
	   * 属性nhsl的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNhsl UFDouble
	   */
	public void setNhsl(UFDouble newNhsl) {
		
		nhsl = newNhsl;
	 } 	  
       
        /**
	   * 属性reserve1的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getReserve1() {
		 return reserve1;
	  }   
	  
     /**
	   * 属性reserve1的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve1 String
	   */
	public void setReserve1(String newReserve1) {
		
		reserve1 = newReserve1;
	 } 	  
       
        /**
	   * 属性reserve16的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFBoolean
	   */
	 public UFBoolean getReserve16() {
		 return reserve16;
	  }   
	  
     /**
	   * 属性reserve16的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve16 UFBoolean
	   */
	public void setReserve16(UFBoolean newReserve16) {
		
		reserve16 = newReserve16;
	 } 	  
       
        /**
	   * 属性nshouldoutnum的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNshouldoutnum() {
		 return nshouldoutnum;
	  }   
	  
     /**
	   * 属性nshouldoutnum的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNshouldoutnum UFDouble
	   */
	public void setNshouldoutnum(UFDouble newNshouldoutnum) {
		
		nshouldoutnum = newNshouldoutnum;
	 } 	  
       
        /**
	   * 属性nloasprice的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNloadprice() {
		 return nloadprice;
	  }   
	  
     /**
	   * 属性nloasprice的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNloasprice UFDouble
	   */
	public void setNloadprice(UFDouble newNloadprice) {
		
		nloadprice = newNloadprice;
	 } 	  
       
        /**
	   * 属性reserve15的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFBoolean
	   */
	 public UFBoolean getReserve15() {
		 return reserve15;
	  }   
	  
     /**
	   * 属性reserve15的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve15 UFBoolean
	   */
	public void setReserve15(UFBoolean newReserve15) {
		
		reserve15 = newReserve15;
	 } 	  
       
        /**
	   * 属性reserve2的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getReserve2() {
		 return reserve2;
	  }   
	  
     /**
	   * 属性reserve2的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve2 String
	   */
	public void setReserve2(String newReserve2) {
		
		reserve2 = newReserve2;
	 } 	  
       
        /**
	   * 属性pk_invmandoc的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getPk_invmandoc() {
		 return pk_invmandoc;
	  }   
	  
     /**
	   * 属性pk_invmandoc的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newPk_invmandoc String
	   */
	public void setPk_invmandoc(String newPk_invmandoc) {
		
		pk_invmandoc = newPk_invmandoc;
	 } 	  
       
        /**
	   * 属性vdef10的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef10() {
		 return vdef10;
	  }   
	  
     /**
	   * 属性vdef10的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef10 String
	   */
	public void setVdef10(String newVdef10) {
		
		vdef10 = newVdef10;
	 } 	  
       
        /**
	   * 属性vdef5的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef5() {
		 return vdef5;
	  }   
	  
     /**
	   * 属性vdef5的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef5 String
	   */
	public void setVdef5(String newVdef5) {
		
		vdef5 = newVdef5;
	 } 	  
       
        /**
	   * 属性cfirstbillbid的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCfirstbillbid() {
		 return cfirstbillbid;
	  }   
	  
     /**
	   * 属性cfirstbillbid的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCfirstbillbid String
	   */
	public void setCfirstbillbid(String newCfirstbillbid) {
		
		cfirstbillbid = newCfirstbillbid;
	 } 	  
       
        /**
	   * 属性reserve4的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getReserve4() {
		 return reserve4;
	  }   
	  
     /**
	   * 属性reserve4的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve4 String
	   */
	public void setReserve4(String newReserve4) {
		
		reserve4 = newReserve4;
	 } 	  
       
        /**
	   * 属性cfirstbillhid的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCfirstbillhid() {
		 return cfirstbillhid;
	  }   
	  
     /**
	   * 属性cfirstbillhid的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCfirstbillhid String
	   */
	public void setCfirstbillhid(String newCfirstbillhid) {
		
		cfirstbillhid = newCfirstbillhid;
	 } 	  
       
        /**
	   * 属性ncodeprice的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNcodeprice() {
		 return ncodeprice;
	  }   
	  
     /**
	   * 属性ncodeprice的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNcodeprice UFDouble
	   */
	public void setNcodeprice(UFDouble newNcodeprice) {
		
		ncodeprice = newNcodeprice;
	 } 	  
       
        /**
	   * 属性vdef7的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef7() {
		 return vdef7;
	  }   
	  
     /**
	   * 属性vdef7的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef7 String
	   */
	public void setVdef7(String newVdef7) {
		
		vdef7 = newVdef7;
	 } 	  
       
        /**
	   * 属性nunloadprice的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNunloadprice() {
		 return nunloadprice;
	  }   
	  
     /**
	   * 属性nunloadprice的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNunloadprice UFDouble
	   */
	public void setNunloadprice(UFDouble newNunloadprice) {
		
		nunloadprice = newNunloadprice;
	 } 	  
       
        /**
	   * 属性ntagprice的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNtagprice() {
		 return ntagprice;
	  }   
	  
     /**
	   * 属性ntagprice的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNtagprice UFDouble
	   */
	public void setNtagprice(UFDouble newNtagprice) {
		
		ntagprice = newNtagprice;
	 } 	  
       
        /**
	   * 属性pk_invbasdoc的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getPk_invbasdoc() {
		 return pk_invbasdoc;
	  }   
	  
     /**
	   * 属性pk_invbasdoc的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newPk_invbasdoc String
	   */
	public void setPk_invbasdoc(String newPk_invbasdoc) {
		
		pk_invbasdoc = newPk_invbasdoc;
	 } 	  
       
        /**
	   * 属性vdef2的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef2() {
		 return vdef2;
	  }   
	  
     /**
	   * 属性vdef2的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef2 String
	   */
	public void setVdef2(String newVdef2) {
		
		vdef2 = newVdef2;
	 } 	  
       
        /**
	   * 属性reserve11的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDate
	   */
	 public UFDate getReserve11() {
		 return reserve11;
	  }   
	  
     /**
	   * 属性reserve11的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve11 UFDate
	   */
	public void setReserve11(UFDate newReserve11) {
		
		reserve11 = newReserve11;
	 } 	  
       
        /**
	   * 属性vmemo的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVmemo() {
		 return vmemo;
	  }   
	  
     /**
	   * 属性vmemo的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVmemo String
	   */
	public void setVmemo(String newVmemo) {
		
		vmemo = newVmemo;
	 } 	  
       
        /**
	   * 属性nassoutnum的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNassoutnum() {
		 return nassoutnum;
	  }   
	  
     /**
	   * 属性nassoutnum的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNassoutnum UFDouble
	   */
	public void setNassoutnum(UFDouble newNassoutnum) {
		
		nassoutnum = newNassoutnum;
	 } 	  
       
        /**
	   * 属性vsourcebillcode的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVsourcebillcode() {
		 return vsourcebillcode;
	  }   
	  
     /**
	   * 属性vsourcebillcode的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVsourcebillcode String
	   */
	public void setVsourcebillcode(String newVsourcebillcode) {
		
		vsourcebillcode = newVsourcebillcode;
	 } 	  
       
        /**
	   * 属性vdef1的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef1() {
		 return vdef1;
	  }   
	  
     /**
	   * 属性vdef1的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef1 String
	   */
	public void setVdef1(String newVdef1) {
		
		vdef1 = newVdef1;
	 } 	  
       
        /**
	   * 属性reserve3的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getReserve3() {
		 return reserve3;
	  }   
	  
     /**
	   * 属性reserve3的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve3 String
	   */
	public void setReserve3(String newReserve3) {
		
		reserve3 = newReserve3;
	 } 	  
       
        /**
	   * 属性csourcebillbid的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCsourcebillbid() {
		 return csourcebillbid;
	  }   
	  
     /**
	   * 属性csourcebillbid的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCsourcebillbid String
	   */
	public void setCsourcebillbid(String newCsourcebillbid) {
		
		csourcebillbid = newCsourcebillbid;
	 } 	  
       
        /**
	   * 属性reserve13的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDate
	   */
	 public UFDate getReserve13() {
		 return reserve13;
	  }   
	  
     /**
	   * 属性reserve13的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve13 UFDate
	   */
	public void setReserve13(UFDate newReserve13) {
		
		reserve13 = newReserve13;
	 } 	  
       
        /**
	   * 属性nassshouldoutnum的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getNassshouldoutnum() {
		 return nassshouldoutnum;
	  }   
	  
     /**
	   * 属性nassshouldoutnum的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newNassshouldoutnum UFDouble
	   */
	public void setNassshouldoutnum(UFDouble newNassshouldoutnum) {
		
		nassshouldoutnum = newNassshouldoutnum;
	 } 	  
       
        /**
	   * 属性reserve9的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getReserve9() {
		 return reserve9;
	  }   
	  
     /**
	   * 属性reserve9的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve9 UFDouble
	   */
	public void setReserve9(UFDouble newReserve9) {
		
		reserve9 = newReserve9;
	 } 	  
       
        /**
	   * 属性reserve8的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getReserve8() {
		 return reserve8;
	  }   
	  
     /**
	   * 属性reserve8的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve8 UFDouble
	   */
	public void setReserve8(UFDouble newReserve8) {
		
		reserve8 = newReserve8;
	 } 	  
       
        /**
	   * 属性vdef9的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef9() {
		 return vdef9;
	  }   
	  
     /**
	   * 属性vdef9的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef9 String
	   */
	public void setVdef9(String newVdef9) {
		
		vdef9 = newVdef9;
	 } 	  
       
        /**
	   * 属性pk_loadprice_b1的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getPk_loadprice_b1() {
		 return pk_loadprice_b1;
	  }   
	  
     /**
	   * 属性pk_loadprice_b1的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newPk_loadprice_b1 String
	   */
	public void setPk_loadprice_b1(String newPk_loadprice_b1) {
		
		pk_loadprice_b1 = newPk_loadprice_b1;
	 } 	  
       
        /**
	   * 属性vdef8的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef8() {
		 return vdef8;
	  }   
	  
     /**
	   * 属性vdef8的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef8 String
	   */
	public void setVdef8(String newVdef8) {
		
		vdef8 = newVdef8;
	 } 	  
       
        /**
	   * 属性cfirsttype的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getCfirsttype() {
		 return cfirsttype;
	  }   
	  
     /**
	   * 属性cfirsttype的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newCfirsttype String
	   */
	public void setCfirsttype(String newCfirsttype) {
		
		cfirsttype = newCfirsttype;
	 } 	  
       
        /**
	   * 属性reserve7的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return UFDouble
	   */
	 public UFDouble getReserve7() {
		 return reserve7;
	  }   
	  
     /**
	   * 属性reserve7的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newReserve7 UFDouble
	   */
	public void setReserve7(UFDouble newReserve7) {
		
		reserve7 = newReserve7;
	 } 	  
       
        /**
	   * 属性vdef6的Getter方法.
	   *
	   * 创建日期:2011-5-3
	   * @return String
	   */
	 public String getVdef6() {
		 return vdef6;
	  }   
	  
     /**
	   * 属性vdef6的Setter方法.
	   *
	   * 创建日期:2011-5-3
	   * @param newVdef6 String
	   */
	public void setVdef6(String newVdef6) {
		
		vdef6 = newVdef6;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2011-5-3
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_loadprice_b1 == null) {
			errFields.add(new String("pk_loadprice_b1"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-5-3
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 		return "pk_loadprice";
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-5-3
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_loadprice_b1";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2011-5-3
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "wds_loadprice_b1";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-5-3
	  */
	public LoadpriceB1VO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2011-5-3
	 * @param newPk_loadprice_b1 主键值
	 */
	 public LoadpriceB1VO(String newPk_loadprice_b1) {
		
		// 为主键字段赋值:
		 pk_loadprice_b1 = newPk_loadprice_b1;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-3
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_loadprice_b1;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2011-5-3
	  * @param newPk_loadprice_b1  String    
	  */
	 public void setPrimaryKey(String newPk_loadprice_b1) {
				
				pk_loadprice_b1 = newPk_loadprice_b1; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2011-5-3
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "wds_loadprice_b1"; 
				
	 }

	public String getCunitid() {
		return cunitid;
	}

	public void setCunitid(String cunitid) {
		this.cunitid = cunitid;
	}

	public String getCassunitid() {
		return cassunitid;
	}

	public void setCassunitid(String cassunitid) {
		this.cassunitid = cassunitid;
	}

	public UFDouble getNtagnum() {
		return ntagnum;
	}

	public void setNtagnum(UFDouble ntagnum) {
		this.ntagnum = ntagnum;
	} 
} 
