/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.zb.comments;

	
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-05-04 11:52:10
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class BidEvalHeaderPrintVO extends BidEvaluationHeaderVO {
	private String 	vzbcode;
	private String vzbname;
	private String deptname;
	private String ywy;
	
	/**
	 * @return java.lang.String[]
	 */
	public String[] getAttributeNames() {
		String[] names = super.getAttributeNames();
		int len = names.length;
		String[] names2 = new String[len+4];
		
		System.arraycopy(names, 0, names2, 0, len);
		names2[len] = "vzbcode";
		names2[len+1] = "vzbname";
		names2[len+2] = "deptname";
		names2[len+3] = "ywy";
		return names2;
	}
	
	public Object getAttributeValue(String name) {
		if (name == null || name.length() == 0)
			return null;
		if(name.equalsIgnoreCase("vzbcode")){
			return getVzbcode();
		}else if(name.equalsIgnoreCase("vzbname"))
			return getVzbname();
		else if(name.equalsIgnoreCase("deptname"))
			return getDeptname();
		else if(name.equalsIgnoreCase("ywy"))
			return getYwy();
		else
			return super.getAttributeValue(name);
	}
	
	/**
	 * 创建日期：(01-3-20 17:24:29)
	 */
	public void setAttributeValue(String name, Object value) {
		if (name == null || name.length() == 0)
			return;
		
		if(name.equalsIgnoreCase("vzbcode")){
			setVzbcode((String)value);
		}else if(name.equalsIgnoreCase("vzbname"))
			setVzbname((String)value);
		else if(name.equalsIgnoreCase("deptname"))
			setDeptname((String)value);
		else if(name.equalsIgnoreCase("ywy"))
			setYwy((String)value);
		else
			 super.setAttributeValue(name,value);
	
	}
	
	public String getVzbcode() {
		return vzbcode;
	}
	public void setVzbcode(String vzbcode) {
		this.vzbcode = vzbcode;
	}
	public String getVzbname() {
		return vzbname;
	}
	public void setVzbname(String vzbname) {
		this.vzbname = vzbname;
	}
	public String getDeptname() {
		return deptname;
	}
	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}
	public String getYwy() {
		return ywy;
	}
	public void setYwy(String ywy) {
		this.ywy = ywy;
	}
	
	
	
} 
