/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.zb.comments;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.scm.pu.PuPubVO;
import nc.vo.zb.pub.ZbPubConst;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-05-04 11:59:50
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class BidSlvendorVO extends SuperVO {
	
	private String cevaluationbid;//评审表子表ID
	private String ccustmanid;//供应商管理ID
	private UFDouble nminnum;//最低报价
	private String crowno;//行号
	private String cslvendorid;//入围供应商表主键
	private UFDouble nzbnum;//中标数量
	private UFDouble nwinpercent;//中标比例
	private UFDouble nzbmny;//中标金额
	private UFBoolean bisfollow;//是否跟标
	private String ccustbasid;//供应商基本ID
	
//	zhf add
	private String cinvbasid;//存货基本id
	private String cinvmanid;//存货管理id
	private UFDouble nquograde;//供应商该品种的报价分
//	zhf end
	
	private UFDateTime ts;
	private UFDouble ndef1;
	private Integer idef2;
	private String vdef1;
	private Integer idef1;
	private String vdef2;
	private String vdef5;
	private UFDouble ndef3;
	private String vdef3;
	private Integer dr;
	private UFDouble ndef2;
	private String vdef4;
	
	public void validataOnSplitNum() throws ValidationException{
//		if(PuPubVO.getString_TrimZeroLenAsNull(getNzbnum())==null || PuPubVO.getString_TrimZeroLenAsNull(getCinvmanid())==null)
//			throw new ValidationException("中标数量为空");
		if(PuPubVO.getString_TrimZeroLenAsNull(getCcustmanid())==null)
			throw new ValidationException("客户信息为空");
		if(PuPubVO.getUFDouble_NullAsZero(getNquograde()).equals(UFDouble.ZERO_DBL)){
			throw new ValidationException("报价分为空");
		}
	}
	
	public void validataOnSaveSplitNum(UFDouble nprice) throws ValidationException{
		if(PuPubVO.getString_TrimZeroLenAsNull(getPrimaryKey())==null){
			throw new ValidationException("数据异常,评审表供应商分量信息表主键为空");
		}
		UFDouble nmny = PuPubVO.getUFDouble_NullAsZero(getNzbmny());
		nmny = nmny.add(UFDouble.ZERO_DBL, ZbPubConst.MNY_DIGIT);
		if(!nmny.equals(PuPubVO.getUFDouble_NullAsZero(getNzbnum()).multiply(nprice, ZbPubConst.MNY_DIGIT))){
			throw new ValidationException("数据异常,中标金额、中标数量、中标单价三者数据不一致");
		}		
	}
	
	


	public static String[] sort_fields = new String[]{"nquograde"};
	
	public static String[] update_fields = new String[]{"nzbnum","nzbmny","nwinpercent"};
			
	public UFDouble getNquograde() {
		return nquograde;
	}
	public void setNquograde(UFDouble nquograde) {
		this.nquograde = nquograde;
	}
	
	public String getCinvbasid() {
		return cinvbasid;
	}
	public void setCinvbasid(String cinvbasid) {
		this.cinvbasid = cinvbasid;
	}
	public String getCinvmanid() {
		return cinvmanid;
	}
	public void setCinvmanid(String cinvmanid) {
		this.cinvmanid = cinvmanid;
	}
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性ndef1的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNdef1 () {
		return ndef1;
	}   
	/**
	 * 属性ndef1的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNdef1 UFDouble
	 */
	public void setNdef1 (UFDouble newNdef1 ) {
	 	this.ndef1 = newNdef1;
	} 	  
	/**
	 * 属性idef2的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public Integer getIdef2 () {
		return idef2;
	}   
	/**
	 * 属性idef2的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newIdef2 UFDouble
	 */
	public void setIdef2 (Integer newIdef2 ) {
	 	this.idef2 = newIdef2;
	} 	  
	/**
	 * 属性ccustmanid的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getCcustmanid () {
		return ccustmanid;
	}   
	/**
	 * 属性ccustmanid的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newCcustmanid String
	 */
	public void setCcustmanid (String newCcustmanid ) {
	 	this.ccustmanid = newCcustmanid;
	} 	  
	/**
	 * 属性nminnum的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNminnum () {
		return nminnum;
	}   
	/**
	 * 属性nminnum的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNminnum UFDouble
	 */
	public void setNminnum (UFDouble newNminnum ) {
	 	this.nminnum = newNminnum;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性idef1的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public Integer getIdef1 () {
		return idef1;
	}   
	/**
	 * 属性idef1的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newIdef1 UFDouble
	 */
	public void setIdef1 (Integer newIdef1 ) {
	 	this.idef1 = newIdef1;
	} 	  
	/**
	 * 属性bisfollow的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFBoolean getBisfollow () {
		return bisfollow;
	}   
	/**
	 * 属性bisfollow的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newBisfollow UFDouble
	 */
	public void setBisfollow (UFBoolean newBisfollow ) {
	 	this.bisfollow = newBisfollow;
	} 	  
	/**
	 * 属性ccustbasid的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getCcustbasid () {
		return ccustbasid;
	}   
	/**
	 * 属性ccustbasid的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newCcustbasid String
	 */
	public void setCcustbasid (String newCcustbasid ) {
	 	this.ccustbasid = newCcustbasid;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性nzbmny的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNzbmny () {
		return nzbmny;
	}   
	/**
	 * 属性nzbmny的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNzbmny UFDouble
	 */
	public void setNzbmny (UFDouble newNzbmny ) {
	 	this.nzbmny = newNzbmny;
	} 	  
	/**
	 * 属性ndef3的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNdef3 () {
		return ndef3;
	}   
	/**
	 * 属性ndef3的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNdef3 UFDouble
	 */
	public void setNdef3 (UFDouble newNdef3 ) {
	 	this.ndef3 = newNdef3;
	} 	  
	/**
	 * 属性crowno的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getCrowno () {
		return crowno;
	}   
	/**
	 * 属性crowno的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newCrowno String
	 */
	public void setCrowno (String newCrowno ) {
	 	this.crowno = newCrowno;
	} 	  
	/**
	 * 属性cslvendorid的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getCslvendorid () {
		return cslvendorid;
	}   
	/**
	 * 属性cslvendorid的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newCslvendorid String
	 */
	public void setCslvendorid (String newCslvendorid ) {
	 	this.cslvendorid = newCslvendorid;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性cevaluationbid的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getCevaluationbid () {
		return cevaluationbid;
	}   
	/**
	 * 属性cevaluationbid的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newCevaluationbid String
	 */
	public void setCevaluationbid (String newCevaluationbid ) {
	 	this.cevaluationbid = newCevaluationbid;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ndef2的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNdef2 () {
		return ndef2;
	}   
	/**
	 * 属性ndef2的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNdef2 UFDouble
	 */
	public void setNdef2 (UFDouble newNdef2 ) {
	 	this.ndef2 = newNdef2;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性nzbnum的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNzbnum () {
		return nzbnum;
	}   
	/**
	 * 属性nzbnum的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNzbnum UFDouble
	 */
	public void setNzbnum (UFDouble newNzbnum ) {
	 	this.nzbnum = newNzbnum;
	} 	  
	/**
	 * 属性nwinpercent的Getter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @return UFDouble
	 */
	public UFDouble getNwinpercent () {
		return nwinpercent;
	}   
	/**
	 * 属性nwinpercent的Setter方法.
	 * 创建日期:2011-05-04 11:59:50
	 * @param newNwinpercent UFDouble
	 */
	public void setNwinpercent (UFDouble newNwinpercent ) {
	 	this.nwinpercent = newNwinpercent;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-05-04 11:59:50
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return "cevaluationbid";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-05-04 11:59:50
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cslvendorid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-05-04 11:59:50
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "zb_slvendor";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-05-04 11:59:50
	  */
     public BidSlvendorVO() {
		super();	
	}    
     
     public void validate() throws ValidationException {
    	 if(PuPubVO.getString_TrimZeroLenAsNull(getCcustmanid())==null){
    		 throw new ValidationException("供应商信息为空");
    	 }
    	 if(PuPubVO.getUFDouble_NullAsZero(getNminnum()).equals(UFDouble.ZERO_DBL)){
    		 throw new ValidationException("供应商最低报价为空");
    	 }
     }
} 
