/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.zb.bidding;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.scm.pu.PuPubVO;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2011-04-28 16:51:42
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class BiddingBodyVO extends SuperVO {
	
	private String crowno;//行号
	private String cunitid;//计量单位
	private UFDouble naverageprice;//历史平均价
	private String cinvbasid;//存货基本ID
	private UFDouble nmarkprice;//标底价
	
	private UFDouble nzbnum;//招标数量
	private String cinvclid;//存货分类ID
	private UFDouble unitweight;//单重
	private UFDouble nplanprice;//计划价
	private UFDouble nmarketprice;//市价
	private String cbiddingbid;//子表主键
	private String cinvmanid;//存货管理ID
	
	private String cupsourcebilltype;
	private String cupsourcebillid;
	private String cupsourcebillrowid;//
	private String csourcetype;
	private String csourcebillhid;
	private String csourcebillbid;
	
//	zhf  add   标书划分时使用：品种大类编码    数据载体 不存在实体
	private transient String invclcode = null;
	
	private String pk_defdoc19;
	private UFDateTime ts;
	private UFDouble reserve10;
	private String vdef9;
	private String pk_defdoc10;
	private UFBoolean reserve15;
	
	private String vdef10;
	private String pk_defdoc18;
	
	private String reserve2;
	private String vdef15;
	private UFDouble reserve8;
	private String pk_defdoc8;
	private String vdef14;
	private String pk_defdoc5;
	private UFDouble reserve7;
	private String vdef7;
	private String pk_defdoc7;
	private UFDate reserve11;////记录标书调整  的调整日期  调整时 占用
	private String vdef2;
	private String vdef16;
	private String vdef5;
	private UFDouble reserve9;
	private String vmemo;
	private String pk_defdoc12;
	private String vdef19;
	private String pk_defdoc13;
	private String pk_defdoc6;
	private String vdef4;
	private String vdef18;
	private String vdef17;
	private String pk_defdoc15;
	private String pk_defdoc2;
	private String vdef20;
	private String vdef1;
	private String vdef8;
	private String reserve5;
	private String cbiddingid;
	private String pk_defdoc3;
	private String pk_defdoc17;
	private UFDate reserve12;
	private String pk_defdoc16;
	private UFDouble reserve6;
	
	private String reserve1;//记录标书调整  的调整操作人  调整时 占用
	private String vdef13;
	private UFBoolean reserve16;
	private UFBoolean reserve14;//----使用  是否调整得来   标书调整处可将其他标段的品种调整过来 来源头id记录 调整来源的头id  来源体已删除
	private String pk_defdoc11;
	private String pk_defdoc9;
	private UFDate reserve13;
	private String vdef11;
	private String pk_defdoc14;
	
	private String pk_defdoc20;
	private String pk_defdoc4;
	private String vdef3;
	private String vdef12;
	private String vdef6;
	private String reserve3;
	private Integer dr;
	private String pk_defdoc1;
	private String reserve4;
		
//	标段划分的基本维度：存货大类
    public static final String[] split_names = new String[]{"invclcode"};
	
	
	public String getInvclcode() {
		return invclcode;
	}
	public void setInvclcode(String invclcode) {
		this.invclcode = invclcode;
	}
	/**
	 * 属性pk_defdoc19的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc19 () {
		return pk_defdoc19;
	}   
	/**
	 * 属性pk_defdoc19的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc19 String
	 */
	public void setPk_defdoc19 (String newPk_defdoc19 ) {
	 	this.pk_defdoc19 = newPk_defdoc19;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性reserve10的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getReserve10 () {
		return reserve10;
	}   
	/**
	 * 属性reserve10的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve10 UFDouble
	 */
	public void setReserve10 (UFDouble newReserve10 ) {
	 	this.reserve10 = newReserve10;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性pk_defdoc10的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc10 () {
		return pk_defdoc10;
	}   
	/**
	 * 属性pk_defdoc10的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc10 String
	 */
	public void setPk_defdoc10 (String newPk_defdoc10 ) {
	 	this.pk_defdoc10 = newPk_defdoc10;
	} 	  
	/**
	 * 属性reserve15的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFBoolean
	 */
	public UFBoolean getReserve15 () {
		return reserve15;
	}   
	/**
	 * 属性reserve15的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve15 UFBoolean
	 */
	public void setReserve15 (UFBoolean newReserve15 ) {
	 	this.reserve15 = newReserve15;
	} 	  
	/**
	 * 属性cupsourcebilltype的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCupsourcebilltype () {
		return cupsourcebilltype;
	}   
	/**
	 * 属性cupsourcebilltype的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCupsourcebilltype String
	 */
	public void setCupsourcebilltype (String newCupsourcebilltype ) {
	 	this.cupsourcebilltype = newCupsourcebilltype;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性pk_defdoc18的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc18 () {
		return pk_defdoc18;
	}   
	/**
	 * 属性pk_defdoc18的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc18 String
	 */
	public void setPk_defdoc18 (String newPk_defdoc18 ) {
	 	this.pk_defdoc18 = newPk_defdoc18;
	} 	  
	/**
	 * 属性csourcebillhid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCsourcebillhid () {
		return csourcebillhid;
	}   
	/**
	 * 属性csourcebillhid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCsourcebillhid String
	 */
	public void setCsourcebillhid (String newCsourcebillhid ) {
	 	this.csourcebillhid = newCsourcebillhid;
	} 	  
	/**
	 * 属性reserve2的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getReserve2 () {
		return reserve2;
	}   
	/**
	 * 属性reserve2的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve2 String
	 */
	public void setReserve2 (String newReserve2 ) {
	 	this.reserve2 = newReserve2;
	} 	  
	/**
	 * 属性crowno的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public String getCrowno () {
		return crowno;
	}   
	/**
	 * 属性crowno的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCrowno UFDouble
	 */
	public void setCrowno (String newCrowno ) {
	 	this.crowno = newCrowno;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性reserve8的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getReserve8 () {
		return reserve8;
	}   
	/**
	 * 属性reserve8的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve8 UFDouble
	 */
	public void setReserve8 (UFDouble newReserve8 ) {
	 	this.reserve8 = newReserve8;
	} 	  
	/**
	 * 属性pk_defdoc8的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc8 () {
		return pk_defdoc8;
	}   
	/**
	 * 属性pk_defdoc8的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc8 String
	 */
	public void setPk_defdoc8 (String newPk_defdoc8 ) {
	 	this.pk_defdoc8 = newPk_defdoc8;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性pk_defdoc5的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc5 () {
		return pk_defdoc5;
	}   
	/**
	 * 属性pk_defdoc5的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc5 String
	 */
	public void setPk_defdoc5 (String newPk_defdoc5 ) {
	 	this.pk_defdoc5 = newPk_defdoc5;
	} 	  
	/**
	 * 属性cunitid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCunitid () {
		return cunitid;
	}   
	/**
	 * 属性cunitid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCunitid String
	 */
	public void setCunitid (String newCunitid ) {
	 	this.cunitid = newCunitid;
	} 	  
	/**
	 * 属性reserve7的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getReserve7 () {
		return reserve7;
	}   
	/**
	 * 属性reserve7的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve7 UFDouble
	 */
	public void setReserve7 (UFDouble newReserve7 ) {
	 	this.reserve7 = newReserve7;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性pk_defdoc7的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc7 () {
		return pk_defdoc7;
	}   
	/**
	 * 属性pk_defdoc7的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc7 String
	 */
	public void setPk_defdoc7 (String newPk_defdoc7 ) {
	 	this.pk_defdoc7 = newPk_defdoc7;
	} 	  
	/**
	 * 属性reserve11的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDate
	 */
	public UFDate getReserve11 () {
		return reserve11;
	}   
	/**
	 * 属性reserve11的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve11 UFDate
	 */
	public void setReserve11 (UFDate newReserve11 ) {
	 	this.reserve11 = newReserve11;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性naverageprice的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getNaverageprice () {
		return naverageprice;
	}   
	/**
	 * 属性naverageprice的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newNaverageprice UFDouble
	 */
	public void setNaverageprice (UFDouble newNaverageprice ) {
	 	this.naverageprice = newNaverageprice;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性reserve9的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getReserve9 () {
		return reserve9;
	}   
	/**
	 * 属性reserve9的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve9 UFDouble
	 */
	public void setReserve9 (UFDouble newReserve9 ) {
	 	this.reserve9 = newReserve9;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性cinvbasid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCinvbasid () {
		return cinvbasid;
	}   
	/**
	 * 属性cinvbasid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCinvbasid String
	 */
	public void setCinvbasid (String newCinvbasid ) {
	 	this.cinvbasid = newCinvbasid;
	} 	  
	/**
	 * 属性pk_defdoc12的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc12 () {
		return pk_defdoc12;
	}   
	/**
	 * 属性pk_defdoc12的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc12 String
	 */
	public void setPk_defdoc12 (String newPk_defdoc12 ) {
	 	this.pk_defdoc12 = newPk_defdoc12;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性nmarkprice的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getNmarkprice () {
		return nmarkprice;
	}   
	/**
	 * 属性nmarkprice的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newNmarkprice UFDouble
	 */
	public void setNmarkprice (UFDouble newNmarkprice ) {
	 	this.nmarkprice = newNmarkprice;
	} 	  
	/**
	 * 属性pk_defdoc13的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc13 () {
		return pk_defdoc13;
	}   
	/**
	 * 属性pk_defdoc13的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc13 String
	 */
	public void setPk_defdoc13 (String newPk_defdoc13 ) {
	 	this.pk_defdoc13 = newPk_defdoc13;
	} 	  
	/**
	 * 属性pk_defdoc6的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc6 () {
		return pk_defdoc6;
	}   
	/**
	 * 属性pk_defdoc6的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc6 String
	 */
	public void setPk_defdoc6 (String newPk_defdoc6 ) {
	 	this.pk_defdoc6 = newPk_defdoc6;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性nzbnum的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getNzbnum () {
		return nzbnum;
	}   
	/**
	 * 属性nzbnum的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newNzbnum UFDouble
	 */
	public void setNzbnum (UFDouble newNzbnum ) {
	 	this.nzbnum = newNzbnum;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性cupsourcebillrowid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCupsourcebillrowid () {
		return cupsourcebillrowid;
	}   
	/**
	 * 属性cupsourcebillrowid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCupsourcebillrowid String
	 */
	public void setCupsourcebillrowid (String newCupsourcebillrowid ) {
	 	this.cupsourcebillrowid = newCupsourcebillrowid;
	} 	  
	/**
	 * 属性pk_defdoc15的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc15 () {
		return pk_defdoc15;
	}   
	/**
	 * 属性pk_defdoc15的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc15 String
	 */
	public void setPk_defdoc15 (String newPk_defdoc15 ) {
	 	this.pk_defdoc15 = newPk_defdoc15;
	} 	  
	/**
	 * 属性pk_defdoc2的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc2 () {
		return pk_defdoc2;
	}   
	/**
	 * 属性pk_defdoc2的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc2 String
	 */
	public void setPk_defdoc2 (String newPk_defdoc2 ) {
	 	this.pk_defdoc2 = newPk_defdoc2;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性cinvclid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCinvclid () {
		return cinvclid;
	}   
	/**
	 * 属性cinvclid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCinvclid String
	 */
	public void setCinvclid (String newCinvclid ) {
	 	this.cinvclid = newCinvclid;
	} 	  
	/**
	 * 属性reserve5的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getReserve5 () {
		return reserve5;
	}   
	/**
	 * 属性reserve5的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve5 String
	 */
	public void setReserve5 (String newReserve5 ) {
	 	this.reserve5 = newReserve5;
	} 	  
	/**
	 * 属性cbiddingid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCbiddingid () {
		return cbiddingid;
	}   
	/**
	 * 属性cbiddingid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCbiddingid String
	 */
	public void setCbiddingid (String newCbiddingid ) {
	 	this.cbiddingid = newCbiddingid;
	} 	  
	/**
	 * 属性pk_defdoc3的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc3 () {
		return pk_defdoc3;
	}   
	/**
	 * 属性pk_defdoc3的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc3 String
	 */
	public void setPk_defdoc3 (String newPk_defdoc3 ) {
	 	this.pk_defdoc3 = newPk_defdoc3;
	} 	  
	/**
	 * 属性pk_defdoc17的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc17 () {
		return pk_defdoc17;
	}   
	/**
	 * 属性pk_defdoc17的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc17 String
	 */
	public void setPk_defdoc17 (String newPk_defdoc17 ) {
	 	this.pk_defdoc17 = newPk_defdoc17;
	} 	  
	/**
	 * 属性cbiddingbid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCbiddingbid () {
		return cbiddingbid;
	}   
	/**
	 * 属性cbiddingbid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCbiddingbid String
	 */
	public void setCbiddingbid (String newCbiddingbid ) {
	 	this.cbiddingbid = newCbiddingbid;
	} 	  
	/**
	 * 属性cinvmanid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCinvmanid () {
		return cinvmanid;
	}   
	/**
	 * 属性cinvmanid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCinvmanid String
	 */
	public void setCinvmanid (String newCinvmanid ) {
	 	this.cinvmanid = newCinvmanid;
	} 	  
	/**
	 * 属性reserve12的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDate
	 */
	public UFDate getReserve12 () {
		return reserve12;
	}   
	/**
	 * 属性reserve12的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve12 UFDate
	 */
	public void setReserve12 (UFDate newReserve12 ) {
	 	this.reserve12 = newReserve12;
	} 	  
	/**
	 * 属性pk_defdoc16的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc16 () {
		return pk_defdoc16;
	}   
	/**
	 * 属性pk_defdoc16的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc16 String
	 */
	public void setPk_defdoc16 (String newPk_defdoc16 ) {
	 	this.pk_defdoc16 = newPk_defdoc16;
	} 	  
	/**
	 * 属性nmarketprice的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getNmarketprice () {
		return nmarketprice;
	}   
	/**
	 * 属性nmarketprice的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newNmarketprice UFDouble
	 */
	public void setNmarketprice (UFDouble newNmarketprice ) {
	 	this.nmarketprice = newNmarketprice;
	} 	  
	/**
	 * 属性reserve6的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getReserve6 () {
		return reserve6;
	}   
	/**
	 * 属性reserve6的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve6 UFDouble
	 */
	public void setReserve6 (UFDouble newReserve6 ) {
	 	this.reserve6 = newReserve6;
	} 	  
	/**
	 * 属性csourcetype的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCsourcetype () {
		return csourcetype;
	}   
	/**
	 * 属性csourcetype的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCsourcetype String
	 */
	public void setCsourcetype (String newCsourcetype ) {
	 	this.csourcetype = newCsourcetype;
	} 	  
	/**
	 * 属性reserve1的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getReserve1 () {
		return reserve1;
	}   
	/**
	 * 属性reserve1的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve1 String
	 */
	public void setReserve1 (String newReserve1 ) {
	 	this.reserve1 = newReserve1;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性nplanprice的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getNplanprice () {
		return nplanprice;
	}   
	/**
	 * 属性nplanprice的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newNplanprice UFDouble
	 */
	public void setNplanprice (UFDouble newNplanprice ) {
	 	this.nplanprice = newNplanprice;
	} 	  
	/**
	 * 属性reserve16的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFBoolean
	 */
	public UFBoolean getReserve16 () {
		return reserve16;
	}   
	/**
	 * 属性reserve16的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve16 UFBoolean
	 */
	public void setReserve16 (UFBoolean newReserve16 ) {
	 	this.reserve16 = newReserve16;
	} 	  
	/**
	 * 属性reserve14的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFBoolean
	 */
	public UFBoolean getReserve14 () {
		return reserve14;
	}   
	/**
	 * 属性reserve14的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve14 UFBoolean
	 */
	public void setReserve14 (UFBoolean newReserve14 ) {
	 	this.reserve14 = newReserve14;
	} 	  
	/**
	 * 属性pk_defdoc11的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc11 () {
		return pk_defdoc11;
	}   
	/**
	 * 属性pk_defdoc11的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc11 String
	 */
	public void setPk_defdoc11 (String newPk_defdoc11 ) {
	 	this.pk_defdoc11 = newPk_defdoc11;
	} 	  
	/**
	 * 属性pk_defdoc9的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc9 () {
		return pk_defdoc9;
	}   
	/**
	 * 属性pk_defdoc9的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc9 String
	 */
	public void setPk_defdoc9 (String newPk_defdoc9 ) {
	 	this.pk_defdoc9 = newPk_defdoc9;
	} 	  
	/**
	 * 属性reserve13的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDate
	 */
	public UFDate getReserve13 () {
		return reserve13;
	}   
	/**
	 * 属性reserve13的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve13 UFDate
	 */
	public void setReserve13 (UFDate newReserve13 ) {
	 	this.reserve13 = newReserve13;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性pk_defdoc14的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc14 () {
		return pk_defdoc14;
	}   
	/**
	 * 属性pk_defdoc14的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc14 String
	 */
	public void setPk_defdoc14 (String newPk_defdoc14 ) {
	 	this.pk_defdoc14 = newPk_defdoc14;
	} 	  
	/**
	 * 属性cupsourcebillid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCupsourcebillid () {
		return cupsourcebillid;
	}   
	/**
	 * 属性cupsourcebillid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCupsourcebillid String
	 */
	public void setCupsourcebillid (String newCupsourcebillid ) {
	 	this.cupsourcebillid = newCupsourcebillid;
	} 	  
	/**
	 * 属性pk_defdoc20的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc20 () {
		return pk_defdoc20;
	}   
	/**
	 * 属性pk_defdoc20的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc20 String
	 */
	public void setPk_defdoc20 (String newPk_defdoc20 ) {
	 	this.pk_defdoc20 = newPk_defdoc20;
	} 	  
	/**
	 * 属性pk_defdoc4的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc4 () {
		return pk_defdoc4;
	}   
	/**
	 * 属性pk_defdoc4的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc4 String
	 */
	public void setPk_defdoc4 (String newPk_defdoc4 ) {
	 	this.pk_defdoc4 = newPk_defdoc4;
	} 	  
	/**
	 * 属性unitweight的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public UFDouble getUnitweight () {
		return unitweight;
	}   
	/**
	 * 属性unitweight的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newUnitweight UFDouble
	 */
	public void setUnitweight (UFDouble newUnitweight ) {
	 	this.unitweight = newUnitweight;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性reserve3的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getReserve3 () {
		return reserve3;
	}   
	/**
	 * 属性reserve3的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve3 String
	 */
	public void setReserve3 (String newReserve3 ) {
	 	this.reserve3 = newReserve3;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_defdoc1的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getPk_defdoc1 () {
		return pk_defdoc1;
	}   
	/**
	 * 属性pk_defdoc1的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newPk_defdoc1 String
	 */
	public void setPk_defdoc1 (String newPk_defdoc1 ) {
	 	this.pk_defdoc1 = newPk_defdoc1;
	} 	  
	/**
	 * 属性reserve4的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getReserve4 () {
		return reserve4;
	}   
	/**
	 * 属性reserve4的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newReserve4 String
	 */
	public void setReserve4 (String newReserve4 ) {
	 	this.reserve4 = newReserve4;
	} 	  
	/**
	 * 属性csourcebillbid的Getter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @return String
	 */
	public String getCsourcebillbid () {
		return csourcebillbid;
	}   
	/**
	 * 属性csourcebillbid的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newCsourcebillbid String
	 */
	public void setCsourcebillbid (String newCsourcebillbid ) {
	 	this.csourcebillbid = newCsourcebillbid;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-04-28 16:51:42
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "cbiddingid";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-04-28 16:51:42
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cbiddingbid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-04-28 16:51:42
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "zb_bidding_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-04-28 16:51:42
	  */
     public BiddingBodyVO() {
		super();	
	}    
     
     public void validateOnSave(boolean isself) throws ValidationException {
    	 if(PuPubVO.getString_TrimZeroLenAsNull(getCrowno()) == null){
    		 throw new ValidationException("行号为空");
    	 }
    	 if(PuPubVO.getString_TrimZeroLenAsNull(getCinvbasid())==null
    			 ||PuPubVO.getString_TrimZeroLenAsNull(getCinvmanid())==null)
    		 throw new ValidationException("品种信息为空");

    	 if(PuPubVO.getUFDouble_NullAsZero(getNzbnum()).equals(UFDouble.ZERO_DBL))
    		 throw new ValidationException("招标数量为空或零");

    	 if(isself)
    		 return;
//    	 if(PuPubVO.getString_TrimZeroLenAsNull(getCsourcetype())==null
//    			 ||PuPubVO.getString_TrimZeroLenAsNull(getCsourcebillhid())==null 
////    			 ||PuPubVO.getString_TrimZeroLenAsNull(getCsourcebillbid())==null
//    			 )
//    		 throw new ValidationException("来源信息为空");
     }
} 
