/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.zb.bidding;
	
import nc.vo.pub.SuperVO;
	
/**
 * 
 * @author zhf 
 * 用于议标数据处理
 *
 */
@SuppressWarnings("serial")
public class SmallBiddingHeaderVO extends SuperVO {
	
	private String cnameno;//名称编码 用于排序显示该标书
	private String cname;//名称
	private String vbillno;//单据号
	private String cbiddingid;//单据主键
	private Integer izbtype;//招标类型
	private Integer ibusstatus;//业务状态
	
	private Integer nvendornum;//供应商入围数量
	
	public Integer getIbusstatus () {
		return ibusstatus;
	}   
	/**
	 * 属性ibusstatus的Setter方法.
	 * 创建日期:2011-04-28 16:51:42
	 * @param newIbusstatus UFDouble
	 */
	public void setIbusstatus (Integer newIbusstatus ) {
	 	this.ibusstatus = newIbusstatus;
	} 	
	public Integer getNvendornum() {
		return nvendornum;
	}
	public void setNvendornum(Integer nvendornum) {
		this.nvendornum = nvendornum;
	}
	public Integer getIzbtype() {
		return izbtype;
	}

	public void setIzbtype(Integer izbtype) {
		this.izbtype = izbtype;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getVbillno() {
		return vbillno;
	}

	public void setVbillno(String vbillno) {
		this.vbillno = vbillno;
	}

	public String getCbiddingid() {
		return cbiddingid;
	}

	public void setCbiddingid(String cbiddingid) {
		this.cbiddingid = cbiddingid;
	}
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2011-04-28 16:51:42
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2011-04-28 16:51:42
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "cbiddingid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2011-04-28 16:51:42
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "zb_bidding_h";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2011-04-28 16:51:42
	  */
     public SmallBiddingHeaderVO() {
		super();	
	}
	public String getCnameno() {
		return cnameno;
	}
	public void setCnameno(String cnameno) {
		this.cnameno = cnameno;
	}
	
} 
