  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.wds.w8006080204;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2010-7-5
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class TbStorareaclVO extends SuperVO {
           
             public String pk_custom9;
             public String pk_stordoc;
             public Integer dr;
             public String pk_custom6;
             public String storname;
             public String srl_customize7;
             public String srl_customize6;
             public String pk_custom2;
             public String srl_name;
             public String srl_customize9;
             public String srl_code;
             public UFTime ts;
             public String pk_custom3;
             public String pk_custom1;
             public String srl_customize4;
             public String pk_custom4;
             public String srl_customize1;
             public String srl_customize3;
             public String vnote;
             public String areaclcode;
             public String srl_pk;
             public String pk_areacl;
             public String srl_customize2;
             public String pk_custom7;
             public String storaddr;
             public String areaclname;
             public String storcode;
             public String srl_customize5;
             public String srl_customize8;
             public String pk_custom8;
             public String pk_custom5;
            
             public static final String  PK_CUSTOM9="pk_custom9";   
             public static final String  PK_STORDOC="pk_stordoc";   
             public static final String  DR="dr";   
             public static final String  PK_CUSTOM6="pk_custom6";   
             public static final String  STORNAME="storname";   
             public static final String  SRL_CUSTOMIZE7="srl_customize7";   
             public static final String  SRL_CUSTOMIZE6="srl_customize6";   
             public static final String  PK_CUSTOM2="pk_custom2";   
             public static final String  SRL_NAME="srl_name";   
             public static final String  SRL_CUSTOMIZE9="srl_customize9";   
             public static final String  SRL_CODE="srl_code";   
             public static final String  TS="ts";   
             public static final String  PK_CUSTOM3="pk_custom3";   
             public static final String  PK_CUSTOM1="pk_custom1";   
             public static final String  SRL_CUSTOMIZE4="srl_customize4";   
             public static final String  PK_CUSTOM4="pk_custom4";   
             public static final String  SRL_CUSTOMIZE1="srl_customize1";   
             public static final String  SRL_CUSTOMIZE3="srl_customize3";   
             public static final String  VNOTE="vnote";   
             public static final String  AREACLCODE="areaclcode";   
             public static final String  SRL_PK="srl_pk";   
             public static final String  PK_AREACL="pk_areacl";   
             public static final String  SRL_CUSTOMIZE2="srl_customize2";   
             public static final String  PK_CUSTOM7="pk_custom7";   
             public static final String  STORADDR="storaddr";   
             public static final String  AREACLNAME="areaclname";   
             public static final String  STORCODE="storcode";   
             public static final String  SRL_CUSTOMIZE5="srl_customize5";   
             public static final String  SRL_CUSTOMIZE8="srl_customize8";   
             public static final String  PK_CUSTOM8="pk_custom8";   
             public static final String  PK_CUSTOM5="pk_custom5";   
      
    
        /**
	   * 属性pk_custom9的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom9() {
		 return pk_custom9;
	  }   
	  
     /**
	   * 属性pk_custom9的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom9 String
	   */
	public void setPk_custom9(String newPk_custom9) {
		
		pk_custom9 = newPk_custom9;
	 } 	  
       
        /**
	   * 属性pk_stordoc的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_stordoc() {
		 return pk_stordoc;
	  }   
	  
     /**
	   * 属性pk_stordoc的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_stordoc String
	   */
	public void setPk_stordoc(String newPk_stordoc) {
		
		pk_stordoc = newPk_stordoc;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性pk_custom6的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom6() {
		 return pk_custom6;
	  }   
	  
     /**
	   * 属性pk_custom6的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom6 String
	   */
	public void setPk_custom6(String newPk_custom6) {
		
		pk_custom6 = newPk_custom6;
	 } 	  
       
        /**
	   * 属性storname的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getStorname() {
		 return storname;
	  }   
	  
     /**
	   * 属性storname的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newStorname String
	   */
	public void setStorname(String newStorname) {
		
		storname = newStorname;
	 } 	  
       
        /**
	   * 属性srl_customize7的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize7() {
		 return srl_customize7;
	  }   
	  
     /**
	   * 属性srl_customize7的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize7 String
	   */
	public void setSrl_customize7(String newSrl_customize7) {
		
		srl_customize7 = newSrl_customize7;
	 } 	  
       
        /**
	   * 属性srl_customize6的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize6() {
		 return srl_customize6;
	  }   
	  
     /**
	   * 属性srl_customize6的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize6 String
	   */
	public void setSrl_customize6(String newSrl_customize6) {
		
		srl_customize6 = newSrl_customize6;
	 } 	  
       
        /**
	   * 属性pk_custom2的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom2() {
		 return pk_custom2;
	  }   
	  
     /**
	   * 属性pk_custom2的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom2 String
	   */
	public void setPk_custom2(String newPk_custom2) {
		
		pk_custom2 = newPk_custom2;
	 } 	  
       
        /**
	   * 属性srl_name的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_name() {
		 return srl_name;
	  }   
	  
     /**
	   * 属性srl_name的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_name String
	   */
	public void setSrl_name(String newSrl_name) {
		
		srl_name = newSrl_name;
	 } 	  
       
        /**
	   * 属性srl_customize9的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize9() {
		 return srl_customize9;
	  }   
	  
     /**
	   * 属性srl_customize9的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize9 String
	   */
	public void setSrl_customize9(String newSrl_customize9) {
		
		srl_customize9 = newSrl_customize9;
	 } 	  
       
        /**
	   * 属性srl_code的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_code() {
		 return srl_code;
	  }   
	  
     /**
	   * 属性srl_code的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_code String
	   */
	public void setSrl_code(String newSrl_code) {
		
		srl_code = newSrl_code;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public UFTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newTs String
	   */
	public void setTs(UFTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性pk_custom3的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom3() {
		 return pk_custom3;
	  }   
	  
     /**
	   * 属性pk_custom3的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom3 String
	   */
	public void setPk_custom3(String newPk_custom3) {
		
		pk_custom3 = newPk_custom3;
	 } 	  
       
        /**
	   * 属性pk_custom1的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom1() {
		 return pk_custom1;
	  }   
	  
     /**
	   * 属性pk_custom1的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom1 String
	   */
	public void setPk_custom1(String newPk_custom1) {
		
		pk_custom1 = newPk_custom1;
	 } 	  
       
        /**
	   * 属性srl_customize4的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize4() {
		 return srl_customize4;
	  }   
	  
     /**
	   * 属性srl_customize4的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize4 String
	   */
	public void setSrl_customize4(String newSrl_customize4) {
		
		srl_customize4 = newSrl_customize4;
	 } 	  
       
        /**
	   * 属性pk_custom4的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom4() {
		 return pk_custom4;
	  }   
	  
     /**
	   * 属性pk_custom4的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom4 String
	   */
	public void setPk_custom4(String newPk_custom4) {
		
		pk_custom4 = newPk_custom4;
	 } 	  
       
        /**
	   * 属性srl_customize1的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize1() {
		 return srl_customize1;
	  }   
	  
     /**
	   * 属性srl_customize1的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize1 String
	   */
	public void setSrl_customize1(String newSrl_customize1) {
		
		srl_customize1 = newSrl_customize1;
	 } 	  
       
        /**
	   * 属性srl_customize3的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize3() {
		 return srl_customize3;
	  }   
	  
     /**
	   * 属性srl_customize3的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize3 String
	   */
	public void setSrl_customize3(String newSrl_customize3) {
		
		srl_customize3 = newSrl_customize3;
	 } 	  
       
        /**
	   * 属性vnote的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getVnote() {
		 return vnote;
	  }   
	  
     /**
	   * 属性vnote的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newVnote String
	   */
	public void setVnote(String newVnote) {
		
		vnote = newVnote;
	 } 	  
       
        /**
	   * 属性areaclcode的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getAreaclcode() {
		 return areaclcode;
	  }   
	  
     /**
	   * 属性areaclcode的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newAreaclcode String
	   */
	public void setAreaclcode(String newAreaclcode) {
		
		areaclcode = newAreaclcode;
	 } 	  
       
        /**
	   * 属性srl_pk的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_pk() {
		 return srl_pk;
	  }   
	  
     /**
	   * 属性srl_pk的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_pk String
	   */
	public void setSrl_pk(String newSrl_pk) {
		
		srl_pk = newSrl_pk;
	 } 	  
       
        /**
	   * 属性pk_areacl的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_areacl() {
		 return pk_areacl;
	  }   
	  
     /**
	   * 属性pk_areacl的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_areacl String
	   */
	public void setPk_areacl(String newPk_areacl) {
		
		pk_areacl = newPk_areacl;
	 } 	  
       
        /**
	   * 属性srl_customize2的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize2() {
		 return srl_customize2;
	  }   
	  
     /**
	   * 属性srl_customize2的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize2 String
	   */
	public void setSrl_customize2(String newSrl_customize2) {
		
		srl_customize2 = newSrl_customize2;
	 } 	  
       
        /**
	   * 属性pk_custom7的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom7() {
		 return pk_custom7;
	  }   
	  
     /**
	   * 属性pk_custom7的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom7 String
	   */
	public void setPk_custom7(String newPk_custom7) {
		
		pk_custom7 = newPk_custom7;
	 } 	  
       
        /**
	   * 属性storaddr的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getStoraddr() {
		 return storaddr;
	  }   
	  
     /**
	   * 属性storaddr的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newStoraddr String
	   */
	public void setStoraddr(String newStoraddr) {
		
		storaddr = newStoraddr;
	 } 	  
       
        /**
	   * 属性areaclname的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getAreaclname() {
		 return areaclname;
	  }   
	  
     /**
	   * 属性areaclname的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newAreaclname String
	   */
	public void setAreaclname(String newAreaclname) {
		
		areaclname = newAreaclname;
	 } 	  
       
        /**
	   * 属性storcode的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getStorcode() {
		 return storcode;
	  }   
	  
     /**
	   * 属性storcode的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newStorcode String
	   */
	public void setStorcode(String newStorcode) {
		
		storcode = newStorcode;
	 } 	  
       
        /**
	   * 属性srl_customize5的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize5() {
		 return srl_customize5;
	  }   
	  
     /**
	   * 属性srl_customize5的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize5 String
	   */
	public void setSrl_customize5(String newSrl_customize5) {
		
		srl_customize5 = newSrl_customize5;
	 } 	  
       
        /**
	   * 属性srl_customize8的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getSrl_customize8() {
		 return srl_customize8;
	  }   
	  
     /**
	   * 属性srl_customize8的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newSrl_customize8 String
	   */
	public void setSrl_customize8(String newSrl_customize8) {
		
		srl_customize8 = newSrl_customize8;
	 } 	  
       
        /**
	   * 属性pk_custom8的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom8() {
		 return pk_custom8;
	  }   
	  
     /**
	   * 属性pk_custom8的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom8 String
	   */
	public void setPk_custom8(String newPk_custom8) {
		
		pk_custom8 = newPk_custom8;
	 } 	  
       
        /**
	   * 属性pk_custom5的Getter方法.
	   *
	   * 创建日期:2010-7-5
	   * @return String
	   */
	 public String getPk_custom5() {
		 return pk_custom5;
	  }   
	  
     /**
	   * 属性pk_custom5的Setter方法.
	   *
	   * 创建日期:2010-7-5
	   * @param newPk_custom5 String
	   */
	public void setPk_custom5(String newPk_custom5) {
		
		pk_custom5 = newPk_custom5;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2010-7-5
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	 	if (pk_areacl == null || "".equals(pk_areacl)) {
			errFields.add(new String("选择地区"));
		}
		if (pk_stordoc == null || "".equals(pk_stordoc)) {
			errFields.add(new String("选择仓库"));
		}
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-7-5
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-7-5
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "srl_pk";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2010-7-5
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "tb_storareacl";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-7-5
	  */
	public TbStorareaclVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2010-7-5
	 * @param newSrl_pk 主键值
	 */
	 public TbStorareaclVO(String newSrl_pk) {
		
		// 为主键字段赋值:
		 srl_pk = newSrl_pk;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-7-5
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return srl_pk;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2010-7-5
	  * @param newSrl_pk  String    
	  */
	 public void setPrimaryKey(String newSrl_pk) {
				
				srl_pk = newSrl_pk; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2010-7-5
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "tb_storareacl"; 
				
	 } 
} 
